### ISSUE TITLE
Kinships[BUG] 

### ISSUE THREAD

**Issue by SpinexLive** [CalderCob/EOA-bug-tracker#1]
### Description of the issue

Kinships are not working. After creating the kin I was able to invite players but then unable to promote etc. When I right click on a player there is no Kinship options. After a relog the kin panel becomes blank saying I need to create or join a kinship. This also happened with the other two who joined.

### Steps To Reproduce

1. Create a kinship
2. Invite other character
3. try to perform actions (kinship based)
4. relog

### Expected Behavior

Normal kin operation being able to view all kin members.

### Where it Happens

All locations

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/74355368/09b326c8-7799-481b-a458-47c8c1447849)

**Comment by SpinexLive** [comment]
I have been advised by another kin they are unable to use Kin chat also.

**Comment by SpinexLive** [comment]
Unsure how, but I have managed to recreate the Kinship by forming another kin with a different name, disbanding it and then I was able to recreate The Silver Blades again. It now seems all issues are working but will monitor and report.

**Comment by CalderCob** [comment]
Re-open another ticket if running into this issue again. Could have been a temporary issue with the server.
