### ISSUE TITLE
Can't go out the Homestead Provision house in Bree Homestead[BUG] 

### ISSUE THREAD

**Issue by damesolena** [CalderCob/EOA-bug-tracker#10]
### Description of the issue

Can't go out the Homestead Provision house in Bree Homestead after i went there to complete Housing quest with Bill Twiggins

### Steps To Reproduce

1. I entered the Homestead Provision house
2. I tried to go out, but nothing happens
3. ...

### Expected Behavior

I should be able to go out ^^'

### Where it Happens

You are at: bx124 by110 c6 ox6.79783 oy-3.10286 oz-18.1185 r57 (Instance 9)

### Entity Information

_If the bug is related to a specific Item, NPC, mob or another selectable object, target the related entity and type !info into /say, then paste the information here. If there are more relevant entities, paste the information for all of them._

### Screenshots

![eoa prob](https://github.com/CalderCob/EOA-bug-tracker/assets/3367417/204cc70f-fe4d-4e4c-9164-78fb91a809c2)

**Comment by echoes-emu** [comment]
Housing is not implemented, you're not supposed to be in there in the 1st place

**Comment by damesolena** [comment]
OK, just that we can do this quest to lead us to the neigborhood. I took the quest in staddle.
