### ISSUE TITLE
[QUEST] Proving Your Quality

### ISSUE THREAD

**Issue by StriBog45** [CalderCob/EOA-bug-tracker#101]
### Quest Name

Proving Your Quality

### Description of the issue

_A clear and concise description of what the problem is._

### Steps To Reproduce

1. Take the horse
2. Run some gates
3. Wait when progress-bar will out

### Expected Behavior

The quest will fail

### Locations

bx118 by127 c0 ox14.9936 oy103.81 oz466.185 r238

### Screenshots

https://www.twitch.tv/videos/1927887497?t=0h47m19s

**Comment by woodx319** [comment]
!quest 700077AE:

**Comment by echoes-emu** [comment]
seems WAI
