### ISSUE TITLE
[QUEST] Plague-bearer of the North

### ISSUE THREAD

**Issue by StriBog45** [CalderCob/EOA-bug-tracker#103]
### Quest Name

Plague-bearer of the North

### Description of the issue

The boss gained complete invulnerability to damage while the damage redirection buff was active, but all minions were dead

### Steps To Reproduce

1. Wait until boss receives the damage redirection buff
2. Kill all minions
3. The boss is invulnerable until the buff ends

### Expected Behavior

The boss becomes vulnerable when all minions die

### Screenshots

https://www.twitch.tv/videos/1927887497?t=7h1m4s

**Comment by woodx319** [comment]
@StriBog45  please provide locations whenever possible. Keep up the good stuff

**Comment by Stressy23** [comment]
Happens to any female Hillmen characters. The one at the top of the steps to helegrod was also unkillable

**Comment by CalderCob** [comment]
If you run into any issues with a specific NPC or object, remember to target the entity and use !info

**Comment by StriBog45** [comment]
Selection: 0x0318D910000003BA (0x0418D91000000003)
 DID: 0x70001764
 Loc: bx141 by145 c0 ox49.2796 oy147.915 oz459.602 r225 (Instance 0)
 Move table: 0x070001BD
 Cosmetic loadout: 0x70002CB8
   melee: Stave
State stack:
(Idle)
Melee combat mode: combat_2h
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by NewsflashFF** [comment]
Some additional info from the same mob type up in Donnvail area:

Selection: 0x0318CA4000000F59 (0x0418CA400000001E)
 DID: 0x70002D1D
 Loc: bx140 by164 c0 ox52.9053 oy69.9255 oz395.071 r164 (Instance 0)
 Move table: 0x070001BD
 Cosmetic loadout: 0x70002D4E
   melee: Stave
State stack:
(Combat)
(Idle)
Melee combat mode: combat_2h
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by echoes-emu** [comment]
Tracked internally: https://github.com/echoes-emu/echoes-bt/issues/1097

**Comment by StriBog45** [comment]
We can't kill the mob because of this buff almost 10 minutes
https://youtu.be/E9QV1l_tmKI?si=TD1CDU75J9rCja3I&t=745

Selection: 0x0318CA400000065D (0x0418CA400000001E)
 DID: 0x70002D1D
 Loc: bx140 by164 c0 ox63.7762 oy77.9893 oz397.034 r73 (Instance 0)
 Move table: 0x070001BD
 Cosmetic loadout: 0x70002D4F
   melee: Stave
State stack:
(RunHome)
(Idle)
Melee combat mode: combat_2h
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by woodx319** [comment]
> We can't kill the mob because of this buff almost 10 minutes

interrupt her to prevent additional applications of the buff (then u can kill)
