### ISSUE TITLE
[CRAFTING BUG] 

### ISSUE THREAD

**Issue by Galadhorn** [CalderCob/EOA-bug-tracker#110]
### Crafting Experience Bug

The character name Grimstick in game. I changed the profession from Woodworker to Armsman by mistake. Then i turned it back. However right after i start crafting forester section. Experience doesnt count and can not get experience to level up. I lost T4 forester profession. This is on going since yesterday evening. I resetted the client etc.

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/145482268/588e9bb9-46a9-4323-89bb-b6d94f2ea917)

**Comment by CalderCob** [comment]
Duplicate
