### ISSUE TITLE
[NPC] Duplicated npc at blackwold headquarters

### ISSUE THREAD

**Issue by Lighwan** [CalderCob/EOA-bug-tracker#111]
Duplicated npc at blackwold headquarters
![image](https://github.com/CalderCob/EOA-bug-tracker/assets/68567124/cf8971c6-2fac-4d3b-b20a-d1dfd703252b)

this pair of lookouts

**Comment by woodx319** [comment]
@Lighwan 

make sure to either provide a location or mob info with the _!info_ command

**Comment by echoes-emu** [comment]
Fixed
