### ISSUE TITLE
[QUEST] Sarnemil's Flight

### ISSUE THREAD

**Issue by NewsflashFF** [CalderCob/EOA-bug-tracker#113]
### Quest Name

Sarnemil's Flight

### Description of the issue

Sarnemil's flight according to previous quest descriptions and guides found online indicates that 2 swarm adds should spawn when Sarnemil is at low health. After pulling the mob, 2 swarm mobs spawned almost immediately, and then shortly after, 2 more swarm mobs spawned as well. Upon trying to run, the mobs teleported to my player character and I was unable to escape.

### Steps To Reproduce

1. Pull Sarnemil
2. Observe add spawns more often than usual

### Expected Behavior

Sarnemil will almost immediately start spawning adds

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in:_
* Quest Giver Location: Daervellas 37.2S, 14.0W
* Problem Location: Sarnemil[39.6S, 14.7W
* Turn in location: Daervellas 37.2S, 14.0W

### Entity Information

Do not have entity info as I was dead

### Screenshots

No video available unfortunately

**Comment by echoes-emu** [comment]
Fixed
