### ISSUE TITLE
[BUG] Death pancake in Retake Weathertop placed incorrectly

### ISSUE THREAD

**Issue by hanrzh** [CalderCob/EOA-bug-tracker#114]
### Description of the issue

Hi, my friend and I were on Retake Weathertop copy quest, touched the dead air wall, which should be a BUG.

### Steps To Reproduce

1. ...my friend and I were on Retake Weathertop copy quest.died on the side road,This is supposed to be the wall of death air.

### Where it Happens

Retake Weathertop copy quest

### Entity Information

wall of death air

### Screenshots
![3be0cc675a180c592ba6f52b7a85b35](https://github.com/CalderCob/EOA-bug-tracker/assets/145791818/235961cf-71a6-452a-8633-11df31cd48d4)

![8c92b07b48ec52ebcd5609659a636d3](https://github.com/CalderCob/EOA-bug-tracker/assets/145791818/d31f4e51-6504-45a6-a6f0-e7432f92190c)

**Comment by woodx319** [comment]
!pe 7000070A:

**Comment by echoes-emu** [comment]
Fixed
