### ISSUE TITLE
[TRAIT] Captain's Hope. Bug with display the deed limit. 

### ISSUE THREAD

**Issue by StriBog45** [CalderCob/EOA-bug-tracker#117]
### Skill Name

Captain's Hope

### Description of the issue

The limit is showing, but the counter keeps increasing

### Steps To Reproduce

1. Reach the deed limit
2. Wait a few days
3. Summon the herald for the deed

### Expected Behavior

The bar will appear blue instead of yellow if there is no limit

### Location

bx158 by114 c0 ox32.0709 oy5.21267 oz330.122 r112

### Screenshots

https://youtu.be/KSu-AUWLHgQ

**Comment by woodx319** [comment]
dupe

https://github.com/CalderCob/EOA-bug-tracker/issues/23
