### ISSUE TITLE
Logging out at Thorins Hall AH[BUG] 

### ISSUE THREAD

**Issue by SpinexLive** [CalderCob/EOA-bug-tracker#12]
### Description of the issue

When you log back in after logging out near Thorins Hall auction house you load in under the map. Reported by 3 members of The Silver Blades

### Steps To Reproduce

Stand near or in the AH at Thorins Hall and log out.
Log back in.
To resolve use /stuck or map home.

### Expected Behavior

Load back into the world as normal
### Where it Happens

bx243 by250 c307 ox-7.69557 oy-35.0237 oz-201.532 r62 (Instance 0)

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/74355368/8e06d1cb-86a6-4054-b280-936c0b8ed6cb)

**Comment by SpinexLive** [comment]
Report from Kin member also states "After clicking the front double doors and loading into Thorin's Hall I ended up under the front stairs"

bx243 by250 c307 ox-7.88425 oy-32.8747 oz-201.973 r254 (Instance 0)

**Comment by echoes-emu** [comment]
This issue is already tracked in the internal bugtracker
