### ISSUE TITLE
LM autoattacks interrupt power of knowledge

### ISSUE THREAD

**Issue by sjstrazdus** [CalderCob/EOA-bug-tracker#122]
### Skill Name

LM's Power of Knowledge

### Description of the issue

If you are autoattacking an enemy and try to use the Power of Knowledge skill it interrupts itself immediately.  I've only tried this solo, so I have aggro, but it happens consistently.  If I turn off autoattacks or if I am too far away to successfully autoattack this issue does not occur.

### Steps To Reproduce

1. get into melee combat with an enemy 
2. make sure auto attacks are on
3. use power of knowledge
4. notice that it immediately aborts

### Expected Behavior

I expect the channel to proceed normally, possibly being pushed back by enemy attacks, but not immediately aborted.

**Comment by echoes-emu** [comment]
Fixed
