### ISSUE TITLE
[BUG] Cancel weapon swing-timer

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#125]
### Description of the issue

remove the cooldown through a clever use of animation cancelling to faster Auto Attack

### Steps To Reproduce

1. auto attack
2. use any skill with a cast bar
3. sidestep as soon as the cast starts
4. auto attack again

### Expected Behavior

to auto attack twice, sometimes three times as fast.

### Where it Happens

anywhere

### Entity Information

any mob

### Screenshots

https://www.youtube.com/watch?v=aIFv2zQ7EE8
https://youtu.be/vgwckYZmu_Q

a nice video.

**Comment by echoes-emu** [comment]
Should be fixed
