### ISSUE TITLE
[BUG] Superior Ancient Iron Jeweller's Tools give incorrect % critical chance

### ISSUE THREAD

**Issue by karasally** [CalderCob/EOA-bug-tracker#127]
### Description of the issue

Superior Ancient Iron Jeweller's Tools give 15% additional critical chance, instead of 16% as displayed on tooltip.
Don't know if this is happening on other tools. 

### Steps To Reproduce

1. Unequip Superior Ancient Iron Jeweller's Tools
2. Critical chance is 5% (just base critical chance)
3. Equip Superior Ancient Iron Jeweller's Tools
4. Critical chance is 20%

### Expected Behavior

Upon equipping Superior Ancient Iron Jeweller's Tools critical chance should be 21%.
Superior Ancient Iron Jeweller's Tools 16% + Base Critical Chance 5% = 21%

### Where it Happens

Anywhere

### Screenshots

Before equipping:  https://imgur.com/a/MAaaQb8
After equipping: https://imgur.com/a/QoIfDos

**Comment by echoes-emu** [comment]
This is just a client UI glitch related to rounding. the actual chance is 20.99999999% which the client renders as 20% for some reason. The server will apply the correct chance
