### ISSUE TITLE
[DEED] Worm Slayer North Downs

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#129]
### Quest Name

Worm Slayer Northdowns and Ram Duath

### Description of the issue

the worms in Ram Duath count for Angmar and not North Downs

### Steps To Reproduce

1. Kill worms in Ram Duath

### Expected Behavior

to progress the Angmar worm slayer deed and not North Downs

### Locations

bx131 by149 c0 ox121.636 oy56.9011 oz459.908 r204 (Instance 0)

### Entity Information

any worm in Ram Duath

### Screenshots

https://youtu.be/HULJtJi9yBU

**Comment by echoes-emu** [comment]
Already tracked internally
