### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TrueZiegmaster** [CalderCob/EOA-bug-tracker#13]
### Description of the issue

Group invite from an instance seems to cause server crash.

### Steps To Reproduce

1. My client crashed inside instance (i was in a group)
2. I asked if my mate can invite me back so i can enter again
3. I got an invite from him
4. When i pressed join button everything stopped and server crashed. 

### Where it Happens

Instance: Secret hideout

### Screenshots
![a](https://github.com/CalderCob/EOA-bug-tracker/assets/27065610/b1f5b9e7-cd06-4888-8c8a-d4803f054bae)

**Comment by echoes-emu** [comment]
Coincidence. The server went down for a different reason
