### ISSUE TITLE
Mischievous Glee CD triggered when no trick on target

### ISSUE THREAD

**Issue by sjstrazdus** [CalderCob/EOA-bug-tracker#130]
### Skill Name

Burglar's Mischievous Glee

### Description of the issue

Mischievous Glee requires an active trick on the target.  If you try to use Mischievous Glee on a target without an active trick you don't get the heal, but the skill goes on cooldown anyway

### Expected Behavior

I expect the skill to completely fail similar to trying to use champ's dirty fighting or merciful strike when the health requirement isn't met.  The skill should not go on cooldown.

**Comment by echoes-emu** [comment]
Fixed
