### ISSUE TITLE
[NPC] Angmar Catapult + Siege Engine

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#131]
### Description of the issue

Angmar Catapult - Siege Engine, (unmoveable but killable objects) stay in combat

### Steps To Reproduce

1. aggro a mob close to the object and run away.
2. check if the object is in combat with you
3. you will be stuck in combat until either you kill the object or log out

### Expected Behavior

the object to stay in combat with you until you log out or kill it

### NPC Information

Selection: 0x031949F000000415 (0x041949F000000005)
 DID: 0x7000120E
 Loc: bx148 by159 c0 ox39.9099 oy111.7 oz370.08 r139 (Instance 0)
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

Selection: 0x031949F000000412 (0x041949F000000004)
 DID: 0x7000120F
 Loc: bx148 by159 c0 ox23.8 oy23.6 oz370.1 r208 (Instance 0)
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

### Where it Happens

Angmar - mobs related to a quest

### Screenshots

https://youtu.be/x9wXZpSyRN4

**Comment by echoes-emu** [comment]
Already tracked internally

**Comment by StriBog45** [comment]
More example

Machine Siege:
Selection: 0x03194A0000000801 (0x04194A0000000003)
 DID: 0x7000120F
 Loc: bx148 by160 c0 ox121.83 oy39.69 oz369.94 r64 (Instance 0)
State stack:
(Combat)
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

Uruk:
Selection: 0x03194A0000000804
 DID: 0x700085C9
 Loc: bx149 by160 c0 ox122.145 oy40.6387 oz386.659 r195 (Instance 0)
 Move table: 0x0700019C
 Cosmetic loadout: 0x7000177A
   melee: sword_big
   ranged: Bow
State stack:
(RunHome)
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_bow
KungFu NPC: No


https://youtu.be/P94rWYSKR1g
https://youtu.be/zox-7yofGdI
