### ISSUE TITLE
[BUG] Critical Chance Craft Bug

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#132]
### Description of the issue

Firstly I would like to request anyone that has had the same problem to react to this post with as much detail as they can remember.
This is not so much a bug report but more a poll to see if others had a similar issue.

Crafting a disproportionate amount of un-critted items.

### Steps To Reproduce

1. I don't know yet how to, but this is what I did before the disproportionate un-critted sequence. (I don't think it is location specific)
2. equipped 18% jeweller tool
3. ran through the door in thorin's hall that leads to the superior workbench
4. read a scroll of ancient jeweller lore (+10%) - total of 33%
5. began crafting 5 glittering platinum necklaces (all at once not clicking to craft each one individually)
6. followed by 10 glittering white gold earring (all at once not clicking to craft each one individually)
7. nothing critted.

### Expected Behavior

I tried it again exactly as written above: this time 9 glittering platinum necklaces and 8 glittering white gold earrings
This time 41% critted.

### Where it Happens

I don't think it is location specific, but it happened here: bx250 by63 c378 ox-151.581 oy-18.8554 oz-172.395 r128 (Instance 0)

### Entity Information

it is not

### Screenshots

_If applicable, add screenshots or a video to help explain your problem._

**Comment by SpinexLive** [comment]
Had 17% base crit chance using superior dwarf steel jeweller tools. also added a 7.5% scroll for 24% crit chance and managed to crit only 2 out of 17 items.

**Comment by Gormundur** [comment]
I have had 0/20 succes sprees at 27%, some of the attempst at 69%, but it was just bad luck i think.
But if i make multiple items at once( queue 10) and get a crit at t4+ where i get the insciption window, the counter will start counting down into the negative and leave me unable to craft anything until i log out

**Comment by echoes-emu** [comment]
Reviewed, the crit chance works correctly so this is 99% just bad luck. Please open a separate ticket for the inscription problem, don't add stuff to unrelated tickets
