### ISSUE TITLE
[NPC] Krahjarn Slayers are elites but not elites 

### ISSUE THREAD

**Issue by Stressy23** [CalderCob/EOA-bug-tracker#133]
### Description of the issue

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/122374802/bfbc011e-00e1-42be-9dcf-218292a9e7e0)
8k hp but classified as a normal mob. It deals damage like a normal mob as I was able to solo it with little to no difficulty. Just a power pot to get through the HP pool 

### Steps To Reproduce

1. Found in northeastern malenhard

### Expected Behavior

Should be classified as an elite

### NPC Information

Selection: 0x031969F000000059
 DID: 0x700085C8
 Loc: bx150 by159 c0 ox91.9429 oy66.6592 oz345.997 r0 (Instance 0)
 Move table: 0x0700019C
 Cosmetic loadout: 0x700012C0
   melee: sword_big
State stack:
(Wander)
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

### Where it Happens

Northeastern Malenhad
### Screenshots

_If applicable, add screenshots or a video to help explain your problem._

**Comment by CalderCob** [comment]
Will be fixed after next maintenance
