### ISSUE TITLE
[BUG] Burglar marbles do not trigger fellowship maneuvers

### ISSUE THREAD

**Issue by Goldenkoron** [CalderCob/EOA-bug-tracker#137]
### Description of the issue

Burglar marbles do not trigger fellowship maneuvers

### Steps To Reproduce

1. Play burglar
2. Join a fellowship
3. Use bag of marbles on an enemy with a member nearby.

### Expected Behavior

Expected behavior is that marbles should trigger a fellowship maneuver when a mob is knocked down.

### Where it Happens

Anywhere, I have tried marbles on monsters in breeland, northdowns, and lonelands to no effect besides a normal knockdown.

### Entity Information

Not sure I can select items. The specific item I have tested is small bag of marbles, but I am told others have tried the other burglar marble items to no effect.

**Comment by Stressy23** [comment]
Level 40 bag of marbles also only causes a stun and not an FM

**Comment by Goldenkoron** [comment]
It's come to my attention that marbles do not initiate FMs in this version of the game. I am closing this report.
