### ISSUE TITLE
Bats in Himbar have normal mob HP

### ISSUE THREAD

**Issue by TurdFerguson79** [CalderCob/EOA-bug-tracker#139]
Bats in Himbar have the green portrait frame indicating Swarm mob, and give out .5 XP commensurate with Swarm mobs, but have the full hit points of a Normal mob.

**Comment by CalderCob** [comment]
> Bats in Himbar have the green portrait frame indicating Swarm mob, and give out .5 XP commensurate with Swarm mobs, but have the full hit points of a Normal mob.

Please target the mob and type !info , post the details here.

**Comment by TurdFerguson79** [comment]
Will try and remember if I get back out there.  

That's the hard thing about testing on Hardcore--I'm out there 100% worried about not dying and only get around to bug reporting after I'm no longer in danger. 😄 If it weren't HC I'd come bug every cow in a tree.

**Comment by echoes-emu** [comment]
Fixed
