### ISSUE TITLE
[BUG] Cineraria's chicken nest under coop

### ISSUE THREAD

**Issue by HurinSteadfast** [CalderCob/EOA-bug-tracker#14]
Cineraria's chicken nest for quest "Which Laid First?" in Shire is misplaced and almost hidden under chicken coop.

Location:  bx90 by115 c0 ox47.0128 oy79.6772 oz363.703 r162 (Instance 0)

If screenshots found online for the quest are to be trusted, the nest should be at:  bx90 by115 c0 ox45.4461 oy86.2008 oz363.703 r190 (Instance 0)

Apologies if this is actually the way it was at original release and I'm just forgetting!

**Comment by echoes-emu** [comment]
This is indeed how it was in SoA
