### ISSUE TITLE
[NPC] The root inside a tree

### ISSUE THREAD

**Issue by StriBog45** [CalderCob/EOA-bug-tracker#144]
### Description of the issue

The mob is inside a tree and cannot be attacked, but he can

### Steps To Reproduce

The mob is always there

### Expected Behavior

The mob will be outside

### NPC Information

Selection: 0x0319278000000025
DID: 0x70007BAC
Loc: bx146 by120 c0 ox118.908 oy138.92 oz339.828 r216 (Instance 0)
KungFu NPC: No

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/32923304/241107a0-baf0-4f22-9bb4-1a51ea31da49)

**Comment by echoes-emu** [comment]
Fixed
