### ISSUE TITLE
Angmar Respawn Rates

### ISSUE THREAD

**Issue by Gormundur** [CalderCob/EOA-bug-tracker#145]
### Description of the issue
Im not sure if this is the right place, but it seems like a bug to me.
Some areas in Angmar have ridiculously high respawn rates that seem to be not intended/bugged. The orc caves between Aughaire and Donnvail are best example. If you try to kill 3 signatures guarding a gate, the first one will respawn before you finish the third. That is with full 6 man group and being overleveled. A similar situation happens in Dun Covad, where the patrols and adds will respawn before you ever have a chance to pull the Lord of the Western Marches.

### Steps To Reproduce

1. Go into the orc cave between Donnvail and Tor Galvin or into the upper levels of Dun Covad
2. Kill signature mob groups
3. Watch as respawn hits you in the back before you finish a single group

### Expected Behavior

For you to be able to clear a group before the first enemy to die respawns

### Where it Happens

Morfil, other orc cave, Dun Covad

### Entity Information

All enemies in specified areas

**Comment by echoes-emu** [comment]
@Gormundur please provide a video or some other way of timing. these mobs should respawn in 3 minutes as any others. Did it take your group 3 minutes to kill the mobs?

**Comment by echoes-emu** [comment]
Bumped the respawn timer for landscape mobs up so this particular situation should be fixed
