### ISSUE TITLE
[SKILL] Blinding Flash

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#147]
### Skill Name

Blinding Flash

### Description of the issue

Blinding Flash has travel time and is not instant

### Steps To Reproduce

1. use blinding flash on a mob 40m away

### Expected Behavior

the mess/daze does not apply instantly / too slow

### Location

any mob

### Entity Information

not applicable

### Screenshots

video of how blinding flash used to work:
https://youtu.be/lyA2z7zsKHw?t=35

video of how blinding flash works now + screenshot of problem
https://youtu.be/AHXTnJ8m_5g
![image](https://github.com/CalderCob/EOA-bug-tracker/assets/15167869/11c69f52-9aba-46e4-9ab9-738ec8ef800e)

**Comment by echoes-emu** [comment]
this is working as intended
