### ISSUE TITLE
Crit labels make counter go negative

### ISSUE THREAD

**Issue by Gormundur** [CalderCob/EOA-bug-tracker#149]
### Description of the issue

when crafting multiple items that can be labeled if crit and a crit occurs, the counter will start counting backwards. If i craft 10 items and crit on the third, it will count down to -6. afterwards i am unable to craft anything at all as the "make" button is greyed out. this is fixed by relogging or circumvented by making items one at a time. only happens at t4 and above due to it being connected to the label dialogue window

### Steps To Reproduce

1. queue up multiple items that can be labeled when crit
2. get lucky early on so it starts counting down into negative

### Expected Behavior

_A clear and concise description of what you expected to happen._

### Where it Happens

_Use /loc in-game and paste the output here. If the problem involves multiple locations, provide all of them. You can also add supplemental information where applicable ("reproduced at X but happens at any stable master" for example)._

### Entity Information

_If the bug is related to a specific Item, NPC, mob or another selectable object, target the related entity and type !info into /say, then paste the information here. If there are more relevant entities, paste the information for all of them._

### Screenshots

_If applicable, add screenshots or a video to help explain your problem._

**Comment by Zakirah1** [comment]
Can confirm this happened to me

**Comment by echoes-emu** [comment]
Fixed
