### ISSUE TITLE
[QUEST] No Session Play for "The Early Bird"

### ISSUE THREAD

**Issue by HurinSteadfast** [CalderCob/EOA-bug-tracker#15]
### Quest Name

The Early Bird

### Description of the issue

This quest requires session play.  Session play does not begin.  Stuck at "waiting to enter session play."

### Steps To Reproduce

1. Receive quest "The Early Bird"
2. Attempt to enter session play at the chicken named "Billina"

### Expected Behavior

Session play begins.

### Locations

bx90 by115 c0 ox67.6714 oy88.2564 oz363.703 r16 (Instance 0)

### Entity Information

Selection: 0x0315A7300000055E (0x0415A73000000049)
 DID: 0x7000AE53
 Loc: bx90 by115 c0 ox68.2046 oy90.2507 oz363.759 r161 (Instance 0)
 Move table: 0x070003B0
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monste

**Comment by echoes-emu** [comment]
Session play is not implemented
