### ISSUE TITLE
[BUG] Hotspot Quest Director randomly appearing in the world

### ISSUE THREAD

**Issue by Shazrah07** [CalderCob/EOA-bug-tracker#151]
### I stumbled across a strange orb labelled "Hotspot Quest Director" and it seems to be very out of place.

_A very out of place orb appeared in multiple spots in the world and I do not believe these are supposed to be visible._

### Steps To Reproduce

1. Not sure if this was part of the reason it spawned but obtain the quests "Ancient Foes of the Spider-Bane", "The Extent of the Threat", and "Raid: Reclaiming Eregion's Gift"
2. Visit the location Loc: bx177 by118 c0 ox125.4 oy7.50914 oz380.341 r0 (Instance 0) in Rivendell.
3. You may see this "Hotspot Quest Director" now.

### Expected Behavior

_These "Hotspot Quest Director" orbs are not supposed to be visible._

### Where it Happens

_Loc: bx177 by118 c0 ox125.4 oy7.50914 oz380.341 r0 (Instance 0)_

### Entity Information

_Selection: 0x031B1760000012FD (0x041B176000000029)
 DID: 0x70000064_

### Screenshots
This is what it looked like in Rivendell, I have yet to come across any others in the world.
![image](https://github.com/CalderCob/EOA-bug-tracker/assets/143241441/c6440021-ec47-4eb4-bf58-85e0f946ee50)

Not my find but a kin member found another one of these next to the friendly mobs "Lorne and Fonn in Angmar. They did not happen to get the !loc or !info at the time.
![image](https://github.com/CalderCob/EOA-bug-tracker/assets/143241441/c7020111-09f2-4994-a9de-fe6af4e10aa3)_

**Comment by echoes-emu** [comment]
Fixed
