### ISSUE TITLE
[HARDCORE DEED] "Epic Volume I" reseted for second character

### ISSUE THREAD

**Issue by StriBog45** [CalderCob/EOA-bug-tracker#155]
### Description of the issue

The achievement "Epic Volume I" reseted for the second character

### Steps To Reproduce

1. Character 1 (Stribog) completes the book 1 chapter 12 at level 17 (with challenge). 
2. Check !hc , that the book 1 achievement completed
3. Character 1 (Stribog) dies
4. Character 2 (Asunayuuki) completes the book 1 chapter 12 at level ~20 (without challenge).
5. Check !hc , that the book 1 achievement uncompleted

### Expected Behavior

The achievement will not be reset for the second character

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/32923304/ef1b504d-bf1e-4ceb-95b4-f359fb8f54ea)

**Comment by woodx319** [comment]
stribog completed insane so non-issue after HC
