### ISSUE TITLE
[NPC] Disgusting Scolopendra (dead) lvl 26-28

### ISSUE THREAD

**Issue by Darkmessin1** [CalderCob/EOA-bug-tracker#156]
### Description of the issue

_Non-disappearing mob corpse_

### Steps To Reproduce

1. Kill the Ancient Bile Death in the wastelands near Nan Dhelu.
2. Kill the scolopendra that appears
3. The remaining corpse of the scolopendra does not disappear anymore

### 

_A clear and concise description of what you expected to happen
![ScreenShot00139](https://github.com/CalderCob/EOA-bug-tracker/assets/147705678/472e4f70-7e99-4440-ae1a-7750e7ce454b)
._

### NPC Information

_Target the affected NPC and type !info into /say, then paste the output in here. If there are more relevant NPCs, include the information for all of them._

### Nan-Dhelu in the Wasteland location

_If only mobs in a specific area are affected, mention it here._

### Screenshots

_If applicable, add screenshots or a video to help explain your problem._

**Comment by echoes-emu** [comment]
Moved to internal bugtracker
