### ISSUE TITLE
Elven Brooch doesn't work

### ISSUE THREAD

**Issue by Headshotman** [CalderCob/EOA-bug-tracker#159]
Hello. 
Item **Elven Brooch** doesn't work for discount. Maybe there are more Brooch for other areas which need on check
![ScreenShot00009](https://github.com/CalderCob/EOA-bug-tracker/assets/148415340/e7673ada-de3a-4c95-b7b8-af70111a890d)
![ScreenShot00010](https://github.com/CalderCob/EOA-bug-tracker/assets/148415340/604e1e7b-c3a1-4889-ab7b-68e2f13da8f3)

**Comment by echoes-emu** [comment]
WAI. This particular vendor doesn't accept the discount
