### ISSUE TITLE
[QUEST] Shore Up the Fence - Flat Field-Stone Keeps Flashing

### ISSUE THREAD

**Issue by HurinSteadfast** [CalderCob/EOA-bug-tracker#16]
### Quest Name
Shore Up the Fence

### Description of the issue

After all field stones have been gathered and you're ready to go back and turn them in, the Flat Field Stone at bx95 by113 c0 ox58.8483 oy44.3387 oz399.559 r82 (Instance 0) continues to flash as though you need to pick it up.

### Locations

bx95 by113 c0 ox58.8483 oy44.3387 oz399.559 r82 (Instance 0)

### Entity Information

Selection: 0x0315F71000000A6B (0x0415F7100000003E)
 DID: 0x70000D63
 Loc: bx95 by113 c0 ox60.2138 oy43.5823 oz399.524 r175 (Instance 0)

**Comment by echoes-emu** [comment]
This is a client-side effect, can't do anything about it
