### ISSUE TITLE
Telling Mark

### ISSUE THREAD

**Issue by Gear2293** [CalderCob/EOA-bug-tracker#161]
### Telling Mark

Captain's skill

### Description of the issue

Telling mark is doing ~2% more melee damage, 4% ranged damage, and +5% tactical damage. I argue this wasn't how it really was in SoA. Instead it should be 10% flat damage increase, from all sources. Just look at revealing mark. 15%, later updated to say it was 15%. Telling mark, same thing, eventually said 10%.

**Comment by woodx319** [comment]
This is confirmed working as intended by devs. And if so likely in the client data

If you're going to make an argument you need some supporting info

'Later updated' When?
'Eventually' When? 

Patch notes?
