### ISSUE TITLE
Sweeping Cut forces too long skill delay, Guardian

### ISSUE THREAD

**Issue by Schaumkus** [CalderCob/EOA-bug-tracker#163]
Skill Name:
Sweeping Cut

Description of the issue:
When you use Sweeping Cut on Guardian, the delay for the skill after it is insanely long.
It is so long, that your character uses two auto attacks before the next skill.
Only Skills that skip that 2 auto attack break, are like Stamp and Retaliation.

1. Use Sweeping Cut on Guardian with 2handed Hammer
2. Use a different skill after
3. Game forces you to do 2 auto attacks before the second skill goes off

Expected Behavior:
Well, no skill in the game should make you wait 2 auto attacks before the next skill goes off.

Video:
https://github.com/CalderCob/EOA-bug-tracker/assets/123096264/28be38d2-1f9b-40da-9670-8dbe44d182bc

**Comment by Barrabornam** [comment]
Fix it!

**Comment by woodx319** [comment]
https://github.com/echoes-emu/echoes-bt/issues/1099

**Comment by echoes-emu** [comment]
Seems to be WAI
