### ISSUE TITLE
Worms in Ram Duath count for wrong Worm-Slayer deed

### ISSUE THREAD

**Issue by sjstrazdus** [CalderCob/EOA-bug-tracker#164]
### Quest Name

Worm-Slayer in North Downs/Angmar

### Description of the issue

Worms in the Ram Duath should count towards the North Downs worm-slayer deed (Defeat worms in the northdowns and Ram Duath).  Right now, only a few in southernmost section of the Ram Duath count towards the north downs deed, the rest count towards the angmar worm-slayer deed.

**Comment by echoes-emu** [comment]
Already tracked internally
