### ISSUE TITLE
Attempting to zone into The Floating Log Inn [BUG] 

### ISSUE THREAD

**Issue by samrien** [CalderCob/EOA-bug-tracker#165]
### Description of the issue

When attempting to 'enter' or zone into The Floating Log Inn, I have trouble doing so. I have noted this on several toons in this same place. I also have noted it happens on occasion in the Auction House in Michel Delving. Worse here

### Steps To Reproduce

1. ...Attempt to enter the Floating Log Inn
2. ...Again Attempt to enter the Floating Log Inn by backing up and reattempting
3. ...Reposition or jump to attempt to enter the Floating Log Inn.

### Expected Behavior

When entering a 'doorway', I expect to be able to enter without delay or issue.

### Where it Happens

_Use /loc in-game and paste the output here. If the problem involves multiple locations, provide all of them. You can also add supplemental information where applicable ("reproduced at X but happens at any stable master" for example)._

### Entity Information

Selection: 0x0316273000001F90 (0x0416273000000050)
 DID: 0x70003B73
 Loc: bx98 by115 c0 ox71.0236 oy148.235 oz338.906 r129 (Instance 0)

### Screenshots
https://drive.google.com/file/d/1aKU_cu1pC2_H11XHs0nOScsaygKQo-fD/view

**Comment by echoes-emu** [comment]
Improved, however the lamp is always going to be an issue for tall races
