### ISSUE TITLE
Inability to use skills or attack after fellowship maneuver 

### ISSUE THREAD

**Issue by Aarmir** [CalderCob/EOA-bug-tracker#166]
### Description of the issue
When a fellowship maneuver concludes, one player still has the fellowship maneuver symbol above their character for the color they hit during the maneuver. The player is unable to use abilities or attack after they have been affected by the bug. 

### Steps To Reproduce the bug:

1. Preferably, have 3-6 or more people for the fellowship maneuver.
2. Use a burglar to force conjunctions with their abilities with  a hunter or loremaster as part of the group. 
3. Have the hunter or loremaster contribute to the conjunction right before the timer expires for inputting a color.

### Expected Behavior

The fellowship maneuver should conclude with every player resuming normal combat with an entity, able to attack and use abilities.

### Where it Happens

This bug has happened in both instanced areas such as Vol 1 Book 2 Chapter 8 The Red Swamp and Fornost to landscape areas such as Nan Wathren. Most likely can be reproduced in any instance with a fellowship or any part of the landscape with a fellowship.

### Entity Information

This bug is not specific to any mob or entity as far as I am aware.

### Screenshots/Videos

https://www.youtube.com/watch?v=2Nw1MesDS9U

*Loremaster experiences bug in fellowship*

###Addendum to fellowship maneuver bug:

1. Ranged classes that use specific color types such as yellows and blues seem to trigger the fellowship maneuver bug more often.
Ex: (Loremaster and Hunter).

3. Contributing to the conjunction with a color right before the timer ends that allows for inputs seems to increase the likelyhood of the bug occuring.

**Comment by echoes-emu** [comment]
when you try using a skill after this happens, what error message do you get on screen/in chat?

**Comment by Aarmir** [comment]
Last time it happened, there was no error message in chat or on screen. The only thing that worked to click on were consumables such as potions and trail food.

**Comment by woodx319** [comment]
https://github.com/echoes-emu/echoes-bt/issues/830

**Comment by woodx319** [comment]
DUPE (both have good info)

https://github.com/CalderCob/EOA-bug-tracker/issues/7

**Comment by echoes-emu** [comment]
Duplicate
