### ISSUE TITLE
Helgrod set piece texture is here to stay

### ISSUE THREAD

**Issue by Gormundur** [CalderCob/EOA-bug-tracker#169]
### Description of the issue

After you ninjadeleted my Helegrod set pieces, the texture is bugged. If i have nothing equipped, it shopws the Helegrod texture as if i still had it equipped. If i wear a new item, the textrue gets stretched and moulded to the worn armour pieces. this only shows in person, not on inspection. Dye doesnt help, relogging doesnt help. maybe a server restart will help, i dont know yet.
I dont really mind that you removed the Set, if you say it was unintended. But if i have to run around with this ugly af stuff, id at least like the stats to make it worth...
looking at these ugly ass shoes makes me really angry

### Steps To Reproduce

1. delete Helegrod set pieces while the wearer is logged out
2. wear no or new armour instead
3. watch them cry upon seeing the constant reminder of what was lost

### Expected Behavior

that the texture vanishes with the item

### Where it Happens

in/on my pants and shoes

### Entity Information

i cant do that since you deleted the item :/

### Screenshots

![ScreenShot00013](https://github.com/CalderCob/EOA-bug-tracker/assets/113916960/e765c076-1eb3-4fcc-b6c8-8d9853dd3f6b)
![ScreenShot00014](https://github.com/CalderCob/EOA-bug-tracker/assets/113916960/f77944dc-0a32-4fc7-935f-cf5d789becd6)
![ScreenShot00015](https://github.com/CalderCob/EOA-bug-tracker/assets/113916960/9863baf9-d82d-48e3-8ae6-c7c27f24b067)
![ScreenShot00016](https://github.com/CalderCob/EOA-bug-tracker/assets/113916960/84f37ad2-e099-42e5-8847-960412fa4042)
![ScreenShot00017](https://github.com/CalderCob/EOA-bug-tracker/assets/113916960/c876766c-e62a-4dd3-b961-bd6ac661d54d)

**Comment by Gormundur** [comment]
The bugfix posted by Chillzor on discord does not work

**Comment by echoes-emu** [comment]
Contact a GM or open a ticket in the Discord
