### ISSUE TITLE
Track Mines [SKILL]

### ISSUE THREAD

**Issue by SpinexLive** [CalderCob/EOA-bug-tracker#17]
### Skill Name

Track Mines

### Description of the issue

Using track mines is not tracking mines on the minimap.

### Steps To Reproduce

Unknown, relog resolves issue.

### Expected Behavior

Mines should appear on the minimap

### Location

All locations.

### Entity Information

Selection: 0x0315975000000547
 DID: 0x7000721A
 Loc: bx89 by117 c0 ox22.9343 oy113.3 oz340.277 r52 (Instance 0)

(Not limited to this one node)

### Screenshots

`![image](https://github.com/CalderCob/EOA-bug-tracker/assets/74355368/8f474437-2400-4dc9-a854-c048f5ba2f6d)

**Comment by echoes-emu** [comment]
Do you have any kind of new repro? did this only happen once or is an intermittent issue?

**Comment by SpinexLive** [comment]
seems to have only been once

**Comment by woodx319** [comment]
i haven't had this happen to me at all

**Comment by echoes-emu** [comment]
Looks like an isolated incident, closing
