### ISSUE TITLE
[QUEST] Oakheart's Flight fails after rescue

### ISSUE THREAD

**Issue by StriBog45** [CalderCob/EOA-bug-tracker#170]
### Quest Name

Oakheart's Flight 

### Description of the issue

The quest failed when we saved Sarah

### Steps To Reproduce

1. Take the quest
2. Escort Sarah outside
3. The quest failed

### Expected Behavior

The quest will complete

### Screenshots

https://clips.twitch.tv/CuriousIgnorantBatteryCmonBruh-qhTHsUpTu9d6S728

**Comment by Goldenkoron** [comment]
I want to back this up that I had this happen as well in my group's Fornost run. We watched Oakheart exit and then it failed. I reported via /tell bug ingame.

**Comment by echoes-emu** [comment]
Reported working now
