### ISSUE TITLE
FM heal not applied despite successful maneuver[BUG] 

### ISSUE THREAD

**Issue by Goldenkoron** [CalderCob/EOA-bug-tracker#176]
### Description of the issue

Sometimes fellowship maneuvers that can apply a heal and HoT do not work.

### Steps To Reproduce

1. Be in a fellowship
2. Do a fellowship maneuver that would normally apply a heal
3. Observe if the heal or HoT is applied to members

### Expected Behavior

A heal and a 14 second heal over time buff should be applied to all members in range

### Where it Happens

I have seen this happen in Fornost and Morroval cave in Ram Duath

### Screenshots

https://drive.google.com/file/d/1z92MLd4prA6XW7HhUV26UWQOMX3hc0fW/view?usp=sharing In this video, the second FM where Wings of the Windlord triggers does not heal anybody or give them the HoT.

https://drive.google.com/file/d/1VFBOLSImcZKG0l6ZD0JtM3uScoxBLcNS/view?usp=sharing In this video, Wrath of the Oathbreakers does not apply a heal or HoT to the group. The maneuver was confirmed successful because two noble spirits are summoned.

**Comment by echoes-emu** [comment]
Videos reviewed, seems to be working, just an unfortunate coincidence

**Comment by Goldenkoron** [comment]
> Videos reviewed, seems to be working, just an unfortunate coincidence

What is the coincidence, is it some kind of line of sight issue for the radius heal when elevation for flooring is weird?
