### ISSUE TITLE
[BUG] Out of World Bounds

### ISSUE THREAD

**Issue by AllyEOA** [CalderCob/EOA-bug-tracker#181]
### Description of the issue
Chat spammed with out of world bounds locations

_A clear and concise description of what the problem is._
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx98 by147 c0 ox54.356 oy108.749 oz391.942 r0 (Instance 0)
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx98 by147 c0 ox54.356 oy108.749 oz391.942 r0 (Instance 0)
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx98 by147 c0 ox54.356 oy108.749 oz391.942 r0 (Instance 0)
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx98 by147 c0 ox54.356 oy108.749 oz391.942 r0 (Instance 0)
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx98 by147 c0 ox54.356 oy108.749 oz391.942 r0 (Instance 0)
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx98 by147 c0 ox54.356 oy108.749 oz391.942 r0 (Instance 0)
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx98 by147 c0 ox54.356 oy108.749 oz391.942 r0 (Instance 0)

### Steps To Reproduce 
Go to the loc mentioned

1. ...
2. ...
3. ...

### Expected Behavior

_A clear and concise description of what you expected to happen._

### Where it Happens

_Use /loc in-game and paste the output here. If the problem involves multiple locations, provide all of them. You can also add supplemental information where applicable ("reproduced at X but happens at any stable master" for example)._
As per chat spam

### Entity Information

_If the bug is related to a specific Item, NPC, mob or another selectable object, target the related entity and type !info into /say, then paste the information here. If there are more relevant entities, paste the information for all of them._

### Screenshots

_If applicable, add screenshots or a video to help explain your problem._

**Comment by echoes-emu** [comment]
Moved to private bug tracker
