### ISSUE TITLE
[BUG] Client Crash

### ISSUE THREAD

**Issue by AllyEOA** [CalderCob/EOA-bug-tracker#182]
### Description of the issue

Client Crash

_A clear and concise description of what the problem is._
I levelled after handing in a quest to Clark Standish in Ost Forod and client crashed and produced a crash log

Echoes Beta Crash Report
========================

Current local time: Sat Nov  4 12:22:09 2023

Error: ACCESS_VIOLATION (0xC0000005) - Write failure at 0xFFFFFFF0

T=18256 (M=18256, C=17472, N=17304, I=19964, V=20072) : 0x8940B480

Call stack:
  0x005BC702 lotroclient.exe
  0x007F4D33 lotroclient.exe
  0x007F4D82 lotroclient.exe
  0x0094CD30 lotroclient.exe
  0x00AD9038 lotroclient.exe
  0x0041D5C7 lotroclient.exe
  0x0094CFB4 lotroclient.exe
  0x00804C3C lotroclient.exe
  0x00840B5A lotroclient.exe
  0x0042A8F0 lotroclient.exe
  0x0042BB4F lotroclient.exe
  0x00431B61 lotroclient.exe
  0x00544B93 lotroclient.exe
  0x005485D7 lotroclient.exe

Registers:
  eax=0xFFFFFFF0 ecx=0x00000001 edx=0x000BD7F1 ebx=0x0019FAAC
  esp=0x0019F9A4 ebp=0x00000001 esi=0x21158678 edi=0x00000003
  eip=0x005BC702 efl=0x00010286

Raw stack:
  0019F920 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0019F930 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0019F940 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0019F950 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0019F960 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0019F970 : 00 00 00 00 00 00 00 00 00 00 00 00 98 F9 19 00 
  0019F980 : 40 FB 19 00 78 86 15 21 70 C8 FA 20 70 C8 FA 20 
  0019F990 : F0 A8 42 00 70 C8 FA 20 70 C8 FA 20 66 BB 42 00 
  0019F9A0 : 70 C8 FA 20 78 86 15 21 AC FA 19 00 03 00 00 00 
  0019F9B0 : 00 00 00 00 C8 01 00 00 70 C8 FA 20 33 4D 7F 00 
  0019F9C0 : 70 C8 FA 20 82 4D 7F 00 78 86 15 21 8C 6B 0E 21 
  0019F9D0 : 18 FB 6A 27 04 00 00 00 AC 71 B0 29 24 85 96 38 
  0019F9E0 : FF FF FF FF 00 0A 00 00 30 CD 94 00 58 E4 D3 2C 
  0019F9F0 : 08 FA 19 00 04 FA 19 00 AC FA 19 00 58 FF 6A 27 
  0019FA00 : 00 7D 00 00 61 2C 00 00 58 01 00 10 90 8B E9 00 
  0019FA10 : 00 00 00 00 00 00 00 00 48 7B BB 00 4C 7A BB 00 

### Steps To Reproduce
Unknown

1. ...
2. ...
3. ...

### Expected Behavior
No Crash

_A clear and concise description of what you expected to happen._

### Where it Happens
Ost Forod, Evendim, by Clark Standish

_Use /loc in-game and paste the output here. If the problem involves multiple locations, provide all of them. You can also add supplemental information where applicable ("reproduced at X but happens at any stable master" for example)._

### Entity Information

_If the bug is related to a specific Item, NPC, mob or another selectable object, target the related entity and type !info into /say, then paste the information here. If there are more relevant entities, paste the information for all of them._

### Screenshots

_If applicable, add screenshots or a video to help explain your problem._

**Comment by echoes-emu** [comment]
Will be fixed in the next patch
