### ISSUE TITLE
[NPC] Brudhraw and Bog-lord

### ISSUE THREAD

**Issue by MaSchm1983** [CalderCob/EOA-bug-tracker#183]
### Description of the issue

We did Book 2 Chapter 6, killing Brudhraw in LL for Emlin. As we pulled him, we noticed, that the group down the stairs (Bog-lord and 2 x Noxious Bog-Warden) are triggered although they are pretty sure not in range for being aggro'd. Well I'm not a 100% sure if this is wanted, but it seem to be not workling the right way? 

### Steps To Reproduce

1. Walking to Brudhraw
2. Pull Brudhraw while ignoring the bog-lord group beneath the boss location
3. Both groups will be pulled

It also works vis versa if you pull the bog-lord, Brudhaw will be activated and running downstairs with his minions

### Expected Behavior

Should imho work properly to pull boch groups alone without triggering the other one?

### NPC Information

Brudhraw, Signature for book2 chapter 6

### Screenshots
![ScreenShot00048](https://github.com/CalderCob/EOA-bug-tracker/assets/74248613/6da35c4a-e7f0-4fd7-9a21-f7304be7e3d1)
![ScreenShot00050](https://github.com/CalderCob/EOA-bug-tracker/assets/74248613/436d697a-42b7-4785-82e7-82927a92b993)
![ScreenShot00051](https://github.com/CalderCob/EOA-bug-tracker/assets/74248613/13b98132-4a7f-4fff-bbea-7cb237c8955a)

**Comment by woodx319** [comment]
Different behavior depending on which one you attack first---

**Brudhraw**
Pulls nothing

**Brud Archer**
Pulls everything lower

**Brud warden**
pulls everything lower

**Bog lord**
pulls everything

**Bog lord archer**
nothing extra

**Bog lord melee**
nothing extra



### MOBS

### UPPER
### Brudhraw
Selection: 0x031926C0000000AC (0x041926C000000021)
 DID: 0x700006E2
 Loc: bx146 by108 c0 ox71.6624 oy26.5811 oz360.08 r0 (Instance 0)
 Move table: 0x0700012C
 Cosmetic loadout: 0x700016F4
   melee: hatchet
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

### Brud Archer
Selection: 0x031926C0000000A9
 DID: 0x70007B78
 Loc: bx146 by108 c0 ox70.4538 oy27.017 oz359.939 r42 (Instance 0)
 Move table: 0x0700012C
 Cosmetic loadout: 0x70002D7C
   melee: sword_small
   ranged: Bow
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_bow
KungFu NPC: No

### Brud Warden
Selection: 0x031926C0000000A8
 DID: 0x70007B65
 Loc: bx146 by108 c0 ox65.1647 oy31.2048 oz360.08 r0 (Instance 0)
 Move table: 0x0700012C
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No


### LOWER


### Bog lord
Selection: 0x031926C0000000A7
 DID: 0x70007B79
 Loc: bx146 by108 c0 ox99.6113 oy59.2695 oz335.328 r0 (Instance 0)
 Move table: 0x0700012C
 Cosmetic loadout: 0x70000CE1
   melee: sword_small
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

### Bog lord archer
Selection: 0x031926C00000009D
 DID: 0x70007B78
 Loc: bx146 by108 c0 ox97.8738 oy53.5236 oz336.358 r166 (Instance 0)
 Move table: 0x0700012C
 Cosmetic loadout: 0x70002D76
   melee: sword_small
   ranged: Bow
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_bow
KungFu NPC: No

### Bog lord warden
Selection: 0x031926C0000000A1
 DID: 0x70007B65
 Loc: bx146 by108 c0 ox94.4692 oy58.0218 oz335.747 r32 (Instance 0)
 Move table: 0x0700012C
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by echoes-emu** [comment]
Working as intended
