### ISSUE TITLE
[BUG] LM is able to slot 1h Sword in main hand

### ISSUE THREAD

**Issue by AllyEOA** [CalderCob/EOA-bug-tracker#184]
### Description of the issue

My (DEAD) LM is able to slot 1h Sword in main hand after server up

### Steps To Reproduce

1. ... Slot 1h Sword
2. ...
3. ...

### Expected Behavior

Not able to slot 1h sword in main hand

### Where it Happens

_Use /loc in-game and paste the output here. If the problem involves multiple locations, provide all of them. You can also add supplemental information where applicable ("reproduced at X but happens at any stable master" for example)._

### Entity Information

_If the bug is related to a specific Item, NPC, mob or another selectable object, target the related entity and type !info into /say, then paste the information here. If there are more relevant entities, paste the information for all of them._

### Screenshots

_If applicable, add screenshots or a video to help explain your problem._

**Comment by AllyEOA** [comment]
![dualw](https://github.com/CalderCob/EOA-bug-tracker/assets/149851193/5c5ec31d-2c53-4d82-84b5-b28344b31b16)

**Comment by TurdFerguson79** [comment]
WAI.  Think you can to this day do that on retail LOTRO.  Now, if you can use *skills* without a staff in MH, that would be a bug.

**Comment by TurdFerguson79** [comment]
Assuming you have Sword&Staff traited

**Comment by echoes-emu** [comment]
WAI
