### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pistoLetoff** [CalderCob/EOA-bug-tracker#188]
My post about only PVP sry for my eng. Maybe some of this isn't a bug. idk
1.  Spider Roots (16s spell) is not knocked down by any damage. 

2.  Dismount animation is so long for PVP chase. 

3. The melee attack radius is very small, you have to be almost in the modeling to hit. This is especially noticeable when the character runs away from you and you run after him.

4. It's very hard to knock someone out of caste (on champ and warg idk about burg) largely due to the GRT system. Maybe these spells should interrupt the animation, I don't know how it was implemented in shadows.

5. We have "combat bug" after pvp at Etten. It takes literally 2-3 minutes of not taking damage to get out of combat

6.  I spend money on repairs after a battle with creeps.

**Comment by echoes-emu** [comment]
Most of this is WAI, probably only the last two issues are valid. Please open one ticket per issue, with proper repro steps
