### ISSUE TITLE
[SKILL] or [TRAIT]  legendary skill sword and staff dual wielding

### ISSUE THREAD

**Issue by sam3Vl** [CalderCob/EOA-bug-tracker#189]
### Skill Name

legendary skill sword and staff dual wielding

### Description of the issue

After installing the legendary sword and staff dual wielding feature, the pet's special effect of flank attack has no effect. After it appears, LM does not have a recovery effect after using witchcraft, or has no effect when using staff strike

### Steps To Reproduce

1. ...Install legendary skill sword and staff dual wielding
2. ...
3. ...

**Comment by echoes-emu** [comment]
Unrelated to the trait. Fixed in next release
