### ISSUE TITLE
[BUG] Invalid mail recipient 

### ISSUE THREAD

**Issue by Diapizio** [CalderCob/EOA-bug-tracker#19]
Unable to send or be sent mail to any character on my account

Whenever a toon tries to mail something to any of my characters they receive the error "Invalid mail recipient" and are unable to send the item. COD does not work as well. For instance if you send mail to my champ "Diapezia " they will receive the error. Seems to be account based. Currently still able to receive auction house mail.

No idea how this occurred in the first place so no means to test for it

Currently happens at every single mailbox. Me and my friends have all tried mailing to my toons and its the same for each toon.

**Comment by woodx319** [comment]
> No idea how this occurred in the first place so no means to test for it

Mail is currently case sensitive, are you capitalizing the first letter?

**Comment by Diapizio** [comment]
> > No idea how this occurred in the first place so no means to test for it
> 
> Mail is currently case sensitive, are you capitalizing the first letter?

No I have not, will see as soon as I get to a mailbox

**Comment by Diapizio** [comment]
> > No idea how this occurred in the first place so no means to test for it
> 
> Mail is currently case sensitive, are you capitalizing the first letter?

This was the issue, thank you!
