### ISSUE TITLE
Raid Captain Bordagor - Grimwood LumberCamp PVMP completing from proximity to camp, not completion of CG kill

### ISSUE THREAD

**Issue by ClemFandangoD** [CalderCob/EOA-bug-tracker#192]
### Quest Name

Raid Captain Bordagor - Grimwood LumberCamp PVMP

### Description of the issue

Quest completing when you scout Lumbercamp if its in FREEP hands, you get a quest completion message, and 2000DP for it completing, merely being in the vicinity of Lumbercamp. Lumbercamp continues to stay as FREEP owned though. So no action on the camp, but the quest completes.I had both this quest and "into the grimwood" scouting quest active. I dont know if the action is interlinked.

### Steps To Reproduce

1. ...With this quest and "into the lumbercamp" active. Move to near the lumbercamp when under Freep control
2. When in the vicinity, a message will pop up, scouted lumbercamp, and then an incorrect "Completed:Raid Captain Bordagor" and 2000 DP is rewarded. The camp stays unflipped
3. ...

### Expected Behavior

Raid Captain Bordagor should only complete when the LC Captain General is killed and the LC flips

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in:_
* Quest Giver Location: _where you obtained the quest_ - Soldier Bagfra Grams Tent bx157 by140 c0 ox95.3596 oy97.6763 oz484.229 r237
* Problem Location: _where the problem occurs_ Lumbercamp (no loc)
* Turn in location: _where you are supposed to finish the quest_ Soldier Bagfra Grams Tent bx157 by140 c0 ox95.3596 oy97.6763 oz484.229 r237

**Comment by echoes-emu** [comment]
Fixed
