### ISSUE TITLE
[SKILL] or [TRAIT]  Several Champion Traits Not Triggering for Progression

### ISSUE THREAD

**Issue by mtk089** [CalderCob/EOA-bug-tracker#194]
### Skill Name

 Eye of the Storm, Patience, and Fervent Rage.  Champion traits

### Description of the issue

These have not triggered for progression.  And my character is level 26.  I'm almost certain they were progressing on the old beta server, and my character was I believe level 21 or 22.

**Comment by echoes-emu** [comment]
You need to be level 30 for these traits
