### ISSUE TITLE
[BUG] "Completed Fellowship Manoeuvres" list remains empty

### ISSUE THREAD

**Issue by rat2156** [CalderCob/EOA-bug-tracker#197]
### Description of the issue

The "Completed Fellowship Manoeuvres" under "Skills"->"Fellowship Skills" remains empty, no matter how many FMs were done successfully

### Steps To Reproduce

1. Constant issue, no need to reproduce

### Expected Behavior

Whenever a new FM is completed, it should display in that list, along with its "recipe" and its effects

**Comment by echoes-emu** [comment]
Fixed
