### ISSUE TITLE
On defeat Skills - Captain [SKILL]

### ISSUE THREAD

**Issue by SpinexLive** [CalderCob/EOA-bug-tracker#2]
### Skill Name

Defeat response skills on Captain

### Description of the issue

Skills on defeat are usable but the toolbar icon stays black and white as if they are unusable

### Steps To Reproduce

unsure, this happened randomly after entering the Mirkstone caves in Thorins gate

### Expected Behavior

On defeat skills should show as usable (with color) after defeating an enemy.

**Comment by CalderCob** [comment]
Temporary fix: Relog

**Comment by woodx319** [comment]
https://github.com/echoes-emu/echoes-bt/issues/335

**Comment by echoes-emu** [comment]
Seems like there is already an internal ticket for this behavior. Might be client-side so not sure if anything can be done about this at all
