### ISSUE TITLE
Fast travel not working as intended [BUG] 

### ISSUE THREAD

**Issue by Shazrah07** [CalderCob/EOA-bug-tracker#20]
### When I tried to fast travel to Celondim my horse would get stuck and I was forced to exit the game and relaunch.

_Upon using the Stable Master in West Bree to fast travel the horse would get stuck after taking one step, even after exiting out completely and relaunching the horse got stuck just outside the West Bree gate._

### Steps To Reproduce

1. Go to the West Bree gate Stable Master
2. Buy a Fast Travel to Celondim or Thorin's Gate

### Expected Behavior

_I expected the horse to complete the animation to take me all the way to Celondim and or Thorin's Hall after purchasing the Swift Travel option._

### Where it Happens
You are at: bx117 by118 c0 ox107.746 oy92.71 oz389.856 r181 (Instance 0) (Horse got stuck here before I relaunched the game.)
You are at: bx116 by118 c0 ox140.458 oy87.0415 oz382.427 r194 (Instance 0). (Horse got stuck here after exiting game and relaunching.

### Entity Information
_This is the info for the Stable Master._
Selection: 0x031757600000042C (0x041757600000000B)
 DID: 0x70003B22
 Loc: bx117 by118 c0 ox109.646 oy97.276 oz389.882 r76 (Instance 0)
 Move table: 0x0700003B
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

### Screenshots
This image is where my horse is stuck after relaunching the game as instructed by the GM, still did not seem to fix the issue.
![image](https://github.com/CalderCob/EOA-bug-tracker/assets/143241441/70ad8fa4-7886-4d77-a33b-c5b076f161ae)

**Comment by woodx319** [comment]
Additional routes with issues:



``Bree to LL``
``Amon Raith to Trestle``
Esteldin to Amon Raith

**Comment by echoes-emu** [comment]
This is already tracked in the internal bugtracker
