### ISSUE TITLE
[BUG] Horse walking doesn't have any animation

### ISSUE THREAD

**Issue by NeuronLi** [CalderCob/EOA-bug-tracker#200]
### Description of the issue

When toggling on walking on a horse, the horse doesn't walk, rather it runs very slowly

### Steps To Reproduce

1. Mount a horse
2. Press the walk button

### Expected Behavior

The horse goes into walking animation.

See video for how the walking animation looks like ingame: https://youtu.be/oZPOhiQt49U

**Comment by echoes-emu** [comment]
that's book 14
