### ISSUE TITLE
Raid Captain General Makan of Tol Ascarnen

### ISSUE THREAD

**Issue by Scoobysnacks86** [CalderCob/EOA-bug-tracker#201]
### **Quest Name**

Raid: Captain General-Makan of Tol Ascarnen (PVMP)

### **Description of the issue**

This quest should finish when CG is killed, and keep is flipped to creep side. Issue is : keep was already flipped for creeps, and upon visiting the tyrant room it completes and awards DP and you get message aabout completeing it.

### **Steps To Reproduce**

1. Take quest in Grams
2. Enter Tol Ascarnen and tyrant room when it's already controlled by creep side
3. Quest finishes and rewards you destiny points

### **Expected Behavior**

This quest should finish when CG is killed, and keep is flipped to creep side.

### **Locations**

_Use /loc in-game to obtain the positions of the following places and paste it in:_
* Quest Giver Location: Gramsfoot: soldier Bagfra
* Problem Location: Tol Ascarnen tyrant/CG room
* Turn in location: think the quest awards you on spot when it's finished, no need to go back to Gramsfoot to hand it in

**Comment by echoes-emu** [comment]
Fixed
