### ISSUE TITLE
[BUG] Dismounting in combat does not work with hotkey (quickslot bar)

### ISSUE THREAD

**Issue by TheRealGnarkill** [CalderCob/EOA-bug-tracker#206]
### Description of the issue

_When mounted and getting into combat the dismount via hotkey does not work anymore (mount item designated to a hotkey) as mounting in combat is forbidden - out of combat everything works as intended. _

### Steps To Reproduce

1. Mount up
2. Get into combat
3. Try to dismount with hotkey

### Expected Behavior

_Not sure if this is WAI - the only way to dismount in combat is if either mobs knock you off or you klick on the bar and confirm._

### Where it Happens

_Location here is irrelevant._

### Entity Information

_not applicable_

### Screenshots

_![ScreenShot00066](https://github.com/CalderCob/EOA-bug-tracker/assets/151951991/a07f5eaa-1b03-4a3e-b512-63b4d4182091)_

**Comment by echoes-emu** [comment]
this is client-side functionality
