### ISSUE TITLE
[QUEST] Of Mysteries Most Profound stays as an Introduction quest after completing it for the first time

### ISSUE THREAD

**Issue by NeuronLi** [CalderCob/EOA-bug-tracker#209]
### Quest Name

Of Mysteries Most Profound -- Introduction

### Description of the issue

For the reputation quests, after completing it once the "-- Introduction" tag disappears from the quest. This is not the case for "Of Mysteries Most Profound -- Introduction"

### Steps To Reproduce

1. Complete "Of Mysteries Most Profound -- Introduction" once
2. Accept the quest another time

### Expected Behavior

The following quests should be called "Of Mysteries Most Profound"

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in:_
* Quest Giver Location: You are at: bx251 by245 c3 ox-64.6216 oy-6.05161 oz-116.096 r115 (Instance 0)
* Problem Location: same location
* Turn in location: same location

**Comment by echoes-emu** [comment]
Tracked internally
