### ISSUE TITLE
Oathie from Fellowship Maneuver reappears

### ISSUE THREAD

**Issue by Nora-elhopanes** [CalderCob/EOA-bug-tracker#21]
### Skill Name

_Fellowship maneuver, I went blue._

### Description of the issue

_The oathbreaker that appeared yesterday when executing a CJ reappears every time I go through a loading screen._

### Steps To Reproduce

1. Do a Fellowship Maneuver that summons oathies
2. Go through a loading screen
3. ...

### Expected Behavior

_Oathbreaker spawns for a short amount of time._

### Location

__

### Entity Information

__

### Screenshots

_If applicable, add screenshots or a video to help explain your problem._
![Skärmbild 2023-08-29 133510](https://github.com/CalderCob/EOA-bug-tracker/assets/122463398/405882d8-1a5d-428d-8515-1be163ea39c0)

Sorry, this was not meant to be quest label

**Comment by echoes-emu** [comment]
This should be fixed now
