### ISSUE TITLE
[NPC] Drakes of Urugarth. All drakes remain aggressive after death

### ISSUE THREAD

**Issue by StriBog45** [CalderCob/EOA-bug-tracker#215]
### Description of the issue
Large drakes of Urugarth do not return to an inactive state after battle. The dragons attack all together upon re-entering the zone.

### Steps To Reproduce

1. Fight only the last drake
2. Every drake became aggressive 
3. Group died
4. Large drakes are active and grouped.

### Expected Behavior
Large drakes will inactive

### NPC Information

_Target the affected NPC and type !info into /say, then paste the output in here. If there are more relevant NPCs, include the information for all of them._

### Where it Happens
Urugarth, side of drakes

### Screenshots
1. We were fighting with last drakes and died  https://youtu.be/SV6A_urw1K8?si=rSSoD8QEJ0uES3Kd&t=2519
2. First attack drakes after retreat. The large drake flew away from us into the air and then attacked   https://youtu.be/SV6A_urw1K8?si=Qw_ZJdnD7VIB0psQ&t=2920
3. Second attack drakes after retreat. Everyone drakes became aggressive.  https://youtu.be/SV6A_urw1K8?si=i6L8Ou3nCfkZQ9oH&t=3051

I guess there are several bugs here, I hope my info will be useful

**Comment by echoes-emu** [comment]
WAI, same as live
