### ISSUE TITLE
[TRAIT] Visual bug in Equipped Traits section of Character Journal

### ISSUE THREAD

**Issue by TheRealGnarkill** [CalderCob/EOA-bug-tracker#217]
### Skill Name

_Visual bug_

### Description of the issue

_After login when I open my Equipped Traits panel via the Character Journal it seems like that the edge of each trait is fully transparent and I can see what's behind (e.g. the object/lightings of the background). It kind of looks like it's edge is moving but it is just the background showing through. When I go to a bard also at the bard panel the issue remains. However after closing the bard window the  character journal part seems to be fixed, upon talking to the bard again it fixed there as well._

### Steps To Reproduce

Managed to reproduce the bug after a logout and log back in 3 times in a row now. You have to move your screen with right klick to see the effect properly.

1. Fresh login
2. Open Charachter Journal go to Traits --> Equipped Traits
3. See the bug
4. Go to a bard and talk to him, still bug remains
5. Close bard window --> bug should be gone now

### Expected Behavior

The Equipped Traits panel should not be partially transparent around the edges of each trait.

### Location

_irrelevant_

### Entity Information

_On lvl 50 Guardian - previously boosted to max._

### Screenshots

![ScreenShot00086](https://github.com/CalderCob/EOA-bug-tracker/assets/151951991/5fd9afee-774f-41c1-b126-c61d91185e17)

**Comment by echoes-emu** [comment]
Client issue, won't fix
