### ISSUE TITLE
Pick up problems in the team[BUG] 

### ISSUE THREAD

**Issue by LEMONER123** [CalderCob/EOA-bug-tracker#220]
### Description of the issue

In the team state, open the throwing mode, not participating in the battle is the player is mining far away, the other side of the player to kill the monster after throwing items, this time, far away mining players can also participate in the throwing

### Where it Happens

A team of 3 players can test, A and B are fighting monsters to throw items, and C is waiting far away on the map

**Comment by echoes-emu** [comment]
the fellowship kill participation distance is cross-checked with live, assumed WAI
