### ISSUE TITLE
[BUG] Logging out from an instance can return the player to their milestone instead of the instance portal

### ISSUE THREAD

**Issue by LEMONER123** [CalderCob/EOA-bug-tracker#223]
### Description of the issue

In the copy, after retreating to the game character interface, the character will appear at the binding point of the map after re-logging in, not at the door of the copy, is this a BUG or deliberate modification

### Expected Behavior

Due to personal reasons or network reasons, log out of the replica to log in again, and want to return to the door of the replica

### Where it Happens

copy

**Comment by echoes-emu** [comment]
Moved to private tracker
