### ISSUE TITLE
[BUG] Vault: taking an item out of vault that is already in inventory causes item's thumbnail to stay in vault

### ISSUE THREAD

**Issue by NeuronLi** [CalderCob/EOA-bug-tracker#225]
### Description of the issue

Items can look like they stay in the vault even though they're already removed from the vault

### Steps To Reproduce

1. Put half of a stack of an item inside the vault
2. Take it off the vault by right clicking it

### Expected Behavior

With bug: the item is looted, but it seems to remain in the vault
Without bug: the item is looted and the icon is removed from the vault

### Where it Happens

Any vault, e.g You are at: bx250 by87 c2 ox3.93329 oy0.140703 oz-28.8015 r194 (Instance 0)

### Video
See repro here. https://youtu.be/LWpBhrhyjRQ
I first demonstrate behaviour without the item, then split it into half and demonstrate the bug, then demonstrate how it removes if you drag it out of the vault instead, then demonstrate how the item doesn't actually exist in the vault.

**Comment by NeuronLi** [comment]
There's a few other bugs related to the vault, which I haven't been able to repro yet. The most annoying one is where you try to move items to the vault but they don't move in vault, they move around in your inventory instead.

**Comment by TheRealGnarkill** [comment]
Can confirm the issue with moving items into the vault but they instead reappear in your bags in a different spot. However, I have also not been able to reproduce it ever since.

**Comment by echoes-emu** [comment]
Tracked internally
