### ISSUE TITLE
[BUG] Mobs turn grey on attack and can't loot uncommon or rarer items off mobs

### ISSUE THREAD

**Issue by NeuronLi** [CalderCob/EOA-bug-tracker#226]
### Description of the issue

When a character has logged off in a fellowship in an instanced area, upon logging back in whenever they attack enemies the enemies turn grey in the same way as if someone else had tagged them and once they're defeated, only common loot can be looted off of the enemies.

### Steps To Reproduce

1. Invite a friend to a fellowship
2. Alt+F4 in an instanced area (AH, Urugarth, etc)
3. Have the friend alt+F4 as well (this is how we reproduced it, but a simple fellowship disband/dismiss might also work)
4. Log back in once the characters have disconnected and fellowship has disbanded
5. Attack an enemy

### Expected Behavior

With bug: Once you attack the enemy, the enemy's health bar and name turn gray. Once the enemy dies and you try to loot the body, you can only loot common items.
Without bug: The enemy's health bar and name remain as the normal colour, all loot can be obtained.

### Where it Happens

Instance to log off reproduced at:
* Urugarth: bx143 by167 c0 ox7.73459 oy134.536 oz604.045 r17 (Instance 2) 
* MD vendor hall: bx250 by85 c6 ox-17.9818 oy-14.2176 oz-27.0093 r130 (Instance 0)
* MD training hall: bx250 by84 c2 ox-0.201188 oy3.99492 oz-15.8113 r0 (Instance 0)

(but it should be reproducible logging off in any instanced area)

### Videos

Urugarth repro: https://youtu.be/DEExIHBVCXQ
Vendor hall repro: https://youtu.be/lqbL58tvZTA

**Comment by echoes-emu** [comment]
Tracked internally with this new repro
