### ISSUE TITLE
[BUG] Urugarth - Lagmas' Court boss fight reset issues after taking the shortcut route

### ISSUE THREAD

**Issue by NeuronLi** [CalderCob/EOA-bug-tracker#228]
### Description of the issue

After taking the shortcut at the dragon boss, when you pull Morthrâng & Co. to the bridge between the shortcut exit and the courtyard, one of the trolls can reset (run back to patrolling the courtyard) while the other two stay engaged

### Steps To Reproduce

1. Take the shortcut route from dragon boss
2. Pull Morthrâng & Co onto the cave end of the bridge connecting the shortcut route to Lagmas' Court

### Expected Behavior

With bug: One of the trolls (not sure which one) resets and goes back to patrolling while the fight continues with the other two mobs. When the two remaining bosses are defeated, the last troll can be fought on his own.
Without bug: All three enemies remain engaged while fighting on the bridge. 

Apologies, I took no screenshots of this happening. We might try it again tonight and will either record it, note down location or mob !info or take screenshots.

**Comment by echoes-emu** [comment]
WAI
