### ISSUE TITLE
Level 30 challenge [BUG] 

### ISSUE THREAD

**Issue by Miti4455** [CalderCob/EOA-bug-tracker#25]
### Description of the issue

After getting to level 30 we received our food reward with !claim, on relog after checking !hc the level 30 challenge moved from completed list back to available challenges.

### Steps To Reproduce

1. Achieve level 30 and !claim
2. Relog
3. ???
4. 0 profit and challenge moved from completed to available

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/143537270/89afa31c-441b-4a2b-8bc0-bfb7df555df5)

**Comment by echoes-emu** [comment]
This should be fixed. You might need to log into your highest level character again to get the achievement
