### ISSUE TITLE
Captains Banner scales wrongly [SKILL] or [TRAIT]

### ISSUE THREAD

**Issue by Miti4455** [CalderCob/EOA-bug-tracker#26]
### Skill Name

Simple Standard of Hope

### Description of the issue

Banners dont scale automaticaly and stay at the level they are crafted, but after planting a banner and then moving through any kind of loading screen the banner respawns at characters level

### Steps To Reproduce

1. Equip captains banner lower level than the captain
2. Plant the banner
3. Walk through a door or crash the game and reenter
4. Banner spawns with you at the captains level, scaling its buff with level
### Expected Behavior

Make them stay at the level they were meant to

**Comment by echoes-emu** [comment]
This should be fixed now
