### ISSUE TITLE
[QUEST] Searching for Fresh Springs Bucket

### ISSUE THREAD

**Issue by woodx319** [CalderCob/EOA-bug-tracker#27]
### Quest Name

Searching for Fresh Springs 

### Description of the issue

When doing this quest each fellowship member has to pick up the bucket. That seems a bit silly, this is listed as a fellowship quest. You're supposed to run back to goldberry x times if you have a full fellow? 

### Steps To Reproduce

Go pick up the bucket

### Expected Behavior

credit should be shared? 

### Locations

Adso 
Selection: 0x031707700000084F (0x0417077000000014)
 DID: 0x70000616
 Loc: bx112 by119 c0 ox84.8839 oy16.9092 oz361.197 r115 (Instance 0)
 Move table: 0x070000B1
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

Bucket
Selection: 0x0316D740000004E7 (0x0416D7400000000A)
 DID: 0x70000618
 Loc: bx109 by116 c0 ox41.8581 oy96.8849 oz386.978 r181 (Instance 0)

**Comment by CalderCob** [comment]
This is how the quest is supposed to work. Although listed as Fellowship, it is quite possible to solo this by the correct route.
