### ISSUE TITLE
Incorrect text message when dismiss party[BUG] 

### ISSUE THREAD

**Issue by rabekon** [CalderCob/EOA-bug-tracker#3]
### Description of the issue

Incorrect text message ("You have lost the trail.") when dismiss party.

### Steps To Reproduce

1. Invite party
2. Dismiss party
3. Look at the chat

### Expected Behavior

That text message ("You have lost the trail.") shouldn't be there.

### Where it Happens

Happens everywhere.

### Screenshots and video

https://youtu.be/TypoOvqVT6g

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/122410042/34ce1948-dd15-4ebb-a1d6-fc0de63b4c15)

**Comment by echoes-emu** [comment]
Fixed
