### ISSUE TITLE
Inviting to fellowship when not FS leader[BUG] 

### ISSUE THREAD

**Issue by SpinexLive** [CalderCob/EOA-bug-tracker#30]
### Description of the issue

By typing /invite (Player Name) they get a prompt to join the fellowship even though you are not the leader. The player cannot accept this.

### Steps To Reproduce

1. Create fellowship and have someone else be leader.
2. As non-leader type /invite (Player Name)

### Expected Behavior

Only fellowship leader should be able to invite

### Where it Happens

All locations

**Comment by echoes-emu** [comment]
Tracked internally
