### ISSUE TITLE
Book 1 chapter 12 HC challenge objective got uncompleted [BUG] 

### ISSUE THREAD

**Issue by lon-eoa** [CalderCob/EOA-bug-tracker#31]
### Description of the issue

I completed book 1 chapter 12, on level (19), and got the HC challenge (showed completed with !hc command). But after a while, it no longer shows as completed.

The same thing happened with the [Reach level 30] challenge. I got it, claimed the food reward, and then lost the completed status. Same as the issue described here https://github.com/CalderCob/EOA-bug-tracker/issues/25

### Steps To Reproduce

1. Complete book 1 chapter 12 on level 19 or below
2. Log out
3. When you log back in the challenge is no longer completed (does not happen to everyone or every time it seems)

### Expected Behavior

The objective should stay completed once it is completed.

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/122407563/e35dec20-8c10-42df-a129-9d24d35a012f)

**Comment by woodx319** [comment]
same ... ;.;

**Comment by echoes-emu** [comment]
This _should_ be fixed. You might need to log back to the character that completed the quest for it to refresh

**Comment by lon-eoa** [comment]
I got the reach level 30 challenge complete now, but still not book 1 chapter 12. Still says: `Complete: Chapter 12: The Black Rider's Designs`

**Comment by kasha695** [comment]
Same as above I still haven't got the book 1 chapter 12 challenge marked as complete. Did it at lvl 17 and it was marked but now has been unmarked. Restarted the client and applied all patches and relogged but not fixed it seems.
