### ISSUE TITLE
[QUEST] Deeds in the wilderness (trollshaws)

### ISSUE THREAD

**Issue by MaSchm1983** [CalderCob/EOA-bug-tracker#32]
### Deeds in the wilderness (Trollshaw quest deed)
Trollshaw deeds in the wilderness  (Stufe 1)

### Description of the issue

I killed some goblins in the LONE LANDS and as I killed the last for tier 1 goblins lone lands deed I turned lvl 20-->21. But another thing happend, I suddenly got the trollshaw deed "deeds in the wilderness" completed too (10/10 quests) although I never put one foot into the troll shaws :D 

### Steps To Reproduce

(Not sure what exactly it triggers but I think it was this:)

1. Finish goblin BDT step 1 in lone lands
2. level up (lvl 20-21 in this case)
3. ...

### Expected Behavior

Since I was was not a time in trollshaws I think nothing should happen here

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in:_

I was about here but I think it doesn't matter for a bug in the deed?
* Problem Location:  You are at: bx135 by113 c0 ox95.7102 oy35.74 oz401.503 r22 (Instance 0)

### Entity Information

Think not, maybe a Goblin between Forsaken Inn and Minas Eriol but I doubt it was the specific goblin. 

### Screenshots

![Screenshot_3](https://github.com/CalderCob/EOA-bug-tracker/assets/74248613/3c76fae6-f944-4c34-9b5e-685658a7eef7)

**Comment by MaSchm1983** [comment]
So I assume there are a few actions linked to this quest somehow. And t1 goblins in lone lands seems to be my 10th so that I could finish. 
Thus we need to find the missing 8 xD

**Comment by MaSchm1983** [comment]
So I guess, it might be more than 10. I yesterday turned 28 again in the lone lands by killing a random lvl 26 warg. I instantly finished the next deed "deeds in the wilderness (advanced)" even though I still not put a food into the trollshaws! :(
![Screenshot_5](https://github.com/CalderCob/EOA-bug-tracker/assets/74248613/83363680-c949-417e-843f-a2892ffcb1cb)

**Comment by echoes-emu** [comment]
Moved to internal bugtracker
