### ISSUE TITLE
Major Combat bug[BUG] 

### ISSUE THREAD

**Issue by TurdFerguson79** [CalderCob/EOA-bug-tracker#33]
I've bugged this in Open Beta and in CBT, so it may be that this issue is too difficult (or impossible) to resolve, but auto attacks and targeting still have one overarching issue with how we interact with enemy mobs.

Auto-attacks are triggering upon skill use and not skill execution, which causes the following issue:  if you're out of range and try and use a skill, you get the normal "you are too far away" message.  But it triggers Auto-Attack on the mob until you deselect it, so that when you then move into range it will start with an auto attack.  It shouldn't happen that way.  

Also, when you change mobs, auto-attack and skill queue should reset, but they currently do not.  Meaning that if you are in combat, and you left click or tab to a mob NOT in combat, it will trigger auto attacks to toggle on that mob.  It makes targeting a nightmare.  

Attacking a new mob should require a right click (if that's your default auto attack key mapping), tilde (which triggers an auto attack) or skill *execution* to engage the mob.  

I think it all comes down to our character not disengaging with mobs at the proper time.  Like, after you kill a mob, it will still have you targeted until you deselect it.  Probably all interconnected, so might end up being something we just have to live with.

What should happen is that every time you change enemies (or cancel/restart combat with the same enemy), combat starts anew.  This is the only bug that has had a noticeable impact on my gameplay, personally.  Otherwise been having a blast through all the testing!

**Comment by echoes-emu** [comment]
Fixed
