### ISSUE TITLE
Barrow Wight Infinite Spawn[NPC] 

### ISSUE THREAD

**Issue by woodx319** [CalderCob/EOA-bug-tracker#34]
### Description of the issue

If you are standing at bx113 by117 c0 ox81.7864 oy81.5832 oz387.676 r21 (Instance 0) the wight will keep on spawning. 

### Steps To Reproduce

Stand on bx113 by117 c0 ox81.7864 oy81.5832 oz387.676 r21 (Instance 0)

### Expected Behavior

Wight shouldn't keep spawning 

### NPC Information

Selection: 0x031717500000077A (0x0417175000000045)
 DID: 0x70007684
 Loc: bx113 by117 c0 ox83.0881 oy82.5934 oz387.596 r166 (Instance 0)
 Move table: 0x0700012C
 Cosmetic loadout: 0x70000CE0
   melee: sword_small
State stack:
(Combat)
(Wander)
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

### Where it Happens

Northern Barrows

### Screenshots

_If applicable, add screenshots or a video to help explain your problem._

**Comment by echoes-emu** [comment]
Fixed
