### ISSUE TITLE
[SKILL] Scholar Nodes don't appear till very close and are not tracked until they appear.

### ISSUE THREAD

**Issue by togreglove** [CalderCob/EOA-bug-tracker#35]
Scholar Profession

Track Artifact

When tracking artifacts, the nodes do not appear on the map until you are within a dozen feet or so.
This also causes the minimap to not show the nodes and definitely not show blue arrows to the nodes.

It is very difficult to locate artifacts in ruins, since they are often hidden in niches with lots of wandering mobs.

1. Enable Track Artifacts
2. Approach a ruins.
3. Note the lack of blue arrows
4. Enter the ruins
5. Get within spitting distance of a node and see it's icon appear

Expected
============
1. Enable Track Artifacts
2. Approach a ruins
3. See one to three blue arrows
4. As you approch the ruins, see the blue arrows turn into node indicators at the edge of the minimap.

**Comment by Tastykake** [comment]
This seems so far to only affect T1 and T2 nodes.  T3 node are tracking properly for me with the blue arrow and the node shows up on the edge of the map.  I can confirm though as Togreglove posted, that T1 and T2 nodes are behaving as they listed.  No blue arrow and the node only appears when you're almost right on top of it.

**Comment by echoes-emu** [comment]
Fixed
