### ISSUE TITLE
[SKILL]Captain: Marks

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#37]
###Captain: Telling Mark & Noble Mark interaction.

_Full name of the skill or trait and what class it belongs to._

### Description of the issue

While in a fellowship with 2 Captains one was using Telling Mark and I was using Noble mark, but Noble mark was overwriting and removing Telling mark from the other captain whenever I used it.

### Steps To Reproduce

1. Have 2 captains.
2. Have 1 captain use telling mark and the second captain use noble mark on the same target.
3. ...

### Expected Behavior

Both Captain marks should be active at the same time and should not cancel each other out as long as they are unique marks.

### Location

-

### Entity Information

-

### Screenshots

-

**Comment by CalderCob** [comment]
This is working as intended, mark stacking became a thing in Book 12.
