### ISSUE TITLE
[BUG] Might stat scaling WAI?

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#39]
### Description of the issue

Might is currently providing verry small offensive power gains, so I'm wondering if the formula is working as intended.
If I increase Might by 6 on my captain, guardian or champion the damage scaling on their abilities goes up by 0,1%. This is so incredibly low that it makes this stat verry underwhelming. I understand you get block/parry and common damage mitigation aswell but for offensive power might is lacking alot. 

### Steps To Reproduce

1. Hover over a damage skill and check the damage scaling on the tooltip.
2. Increase your characters might by 6. And check the tooltip again.
3. ...

### Expected Behavior

Is might supposed to give more damage scaling? Is the current formula of 6 might = 0,1% damage working as intended?

### Where it Happens

-

### Entity Information

-

### Screenshots

https://imgur.com/a/jQvEuOG

**Comment by woodx319** [comment]
WAI? probably

**Comment by CalderCob** [comment]
Might scaling has been updated to match references.
