### ISSUE TITLE
Food icon under portrait

### ISSUE THREAD

**Issue by samrien** [CalderCob/EOA-bug-tracker#41]
### Description of the issue

After my toon consumed a Mushroom Pie, which lasts 1min, the food icon under my portrait began to blink to warn of imminent expiration but it did not stop blinking or disappear.  I'm not receiving a food buff, yet the icon remains under my portrait blinking.

Logging out and back in stopped the behavior.

### Expected Behavior

I expected the buff and the blinking food buff icon to expire after the 1min timer was exhausted.

### Where it Happens

bx91 by115 c0 ox147.599 oy100.337 oz376.838 r124 (Instance 0)  

Not sure if it is a general, random bug, but I experienced this behavior after consuming a Mushroom Pie.

**Comment by woodx319** [comment]
This may be working or improved after eating a mushroom pie with no issues

**Comment by echoes-emu** [comment]
_should_ be fixed now
