### ISSUE TITLE
Riding quest not working: Fresh steed for Bree [QUEST] 

### ISSUE THREAD

**Issue by lon-eoa** [CalderCob/EOA-bug-tracker#42]
### Quest Name

Fresh steed for Bree

### Description of the issue

You are supposed to ride a horse from Hengstacer to the west Bree gate stables, but nothing happens when you arrive there. The horse is supposed to automatically despawn, and then the quest objective should update.

### Steps To Reproduce

1. Pick up the quest from Eogar at Hengstacer (lvl 35)
2. Mount the Blonde Sorrel steed and ride it to the west Bree gate stable master
3. Once you arrive, nothing happens.

### Expected Behavior

Once you arrive at the west Bree stable master riding the horse, it should automatically despawn and the quest objective should update.

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in:_
* Quest Giver Location:  bx118 by127 c0 ox12.279 oy103.997 oz466.145 r64 (Instance 0)
* Problem Location: bx117 by118 c0 ox109.646 oy97.276 oz389.882 r85 (Instance 0)
* Turn in location:  bx118 by127 c0 ox12.279 oy103.997 oz466.145 r64 (Instance 0)

### Entity Information

The ridable horse for the quest: 
Selection: 0x031767F000001355 (0x041767F00000001B)
DID: 0x70009AB5
Loc: bx118 by127 c0 ox8.27729 oy97.7187 oz466.169 r64 (Instance 0)

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/122407563/c3eada9e-251a-4526-b98d-f713e6b60ade)

**Comment by echoes-emu** [comment]
Should be fixed

**Comment by erikshaydulin** [comment]
nice, ty
