### ISSUE TITLE
[NPC] Garth Agarwen Instance

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#45]
### Description of the issue

Garth Agarwen - Last boss Naruhel - has 2 bugs (maybe 3).
In phase 1 the adds do not automatically attack: https://youtu.be/F8uRS2UpSns?t=6892
Naruhel AOE ability does not knockback: https://youtu.be/F8uRS2UpSns?t=7182
In the last phase she has some weird behavior and inability to be attacked: https://youtu.be/F8uRS2UpSns?t=7266

### Steps To Reproduce

1. Fight her

### Expected Behavior

it to bug

### NPC Information

sorry have no way to get back into Garth Agarwen instance, but it is the last boss

### Where it Happens

Garth Agarwen last boss Naruhel

### Screenshots

Video of the full fight: https://youtu.be/F8uRS2UpSns?t=6876
Video of the full fight 2007 of the original fight: https://www.youtube.com/watch?v=7Sh-6HscyjU&t=4s

**Comment by echoes-emu** [comment]
All these issues are now tracked internally
