### ISSUE TITLE
Horse Travel from bree > forsaken Inn[BUG] 

### ISSUE THREAD

**Issue by SpinexLive** [CalderCob/EOA-bug-tracker#48]
### Description of the issue

Using the horse travel from Bree South-Gate to Forsaken Inn stops partway.

### Steps To Reproduce

1. Purchase travel to Forsaken Inn from South Bree
2. ride on horse.

### Expected Behavior

Expected to finish my journey.

### Where it Happens

bx123 by114 c0 ox39.9866 oy98.2719 oz384.66 r192 (Instance 0)

**Comment by echoes-emu** [comment]
Already tracked in other tickets
