### ISSUE TITLE
Frog Swimming in Air [BUG] 

### ISSUE THREAD

**Issue by samrien** [CalderCob/EOA-bug-tracker#49]
### Description of the issue

Was questing in the Frogmoors and noticed a wild hill-toad swimming in air

### Steps To Reproduce

Just there.

### Expected Behavior

Wild Hill-Toads should be swimming in water.

### Where it Happens

bx99 by116 c0 ox121.728 oy18.6074 oz341.222 r221 (Instance 0)
### Screenshots

![swimairfrog](https://github.com/CalderCob/EOA-bug-tracker/assets/143850917/95d83be3-9f6d-4fb9-892b-4a5bb3ad5a64)

**Comment by echoes-emu** [comment]
Fixed
