### ISSUE TITLE
Fish Swimming in Air [BUG] 

### ISSUE THREAD

**Issue by samrien** [CalderCob/EOA-bug-tracker#50]
### Description of the issue

While questing in the Rushock Bog, I noticed that a fish was swimming above the water line

### Steps To Reproduce

It is just a visual anomaly always there

### Expected Behavior

The fish should be in the water

### Where it Happens

_Use /loc in-game and paste the output here. If the problem involves multiple locations, provide all of them. You can also add supplemental information where applicable ("reproduced at X but happens at any stable master" for example)._

### Entity Information

bx88 by119 c0 ox129.342 oy153.979 oz336.936 r149 (Instance 0)

### Screenshots
![image](https://github.com/CalderCob/EOA-bug-tracker/assets/143850917/77ba53fd-092a-4e22-b1eb-1f421a90f726)

**Comment by CalderCob** [comment]
This is a client side issue.
