### ISSUE TITLE
World border issue[BUG] 

### ISSUE THREAD

**Issue by Miti4455** [CalderCob/EOA-bug-tracker#51]
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx90 by148 c0 ox159.583 oy0.168777 oz445.528 r0 (Instance 0)

Western Evendim, a random world border where it shouldn't be

**Comment by Miti4455** [comment]
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx98 by139 c0 ox159.962 oy158.189 oz338.132 r0 (Instance 0)

one issue in tinnudir too

**Comment by CalderCob** [comment]
Out of world bounds issues for Evendim seems to be fixed. Submit another ticket if you run into more of these issues.
