### ISSUE TITLE
[RE-OPENED] Book 1 chapter 12 HC challenge objective got uncompleted [BUG] 

### ISSUE THREAD

**Issue by lon-eoa** [CalderCob/EOA-bug-tracker#52]
### Description of the issue

Reopening of https://github.com/CalderCob/EOA-bug-tracker/issues/31. I still don't have it, and other people have the same problem too.

I completed book 1 chapter 12, on level (19), and got the HC challenge (showed completed with !hc command). But after a while, it no longer shows as completed.

### Steps To Reproduce

1. Complete book 1 chapter 12 on level 19 or below
2. Log out
3. When you log back in the challenge is no longer completed (does not happen to everyone or every time it seems)

### Expected Behavior

The objective should stay completed once it is completed.

**Comment by woodx319** [comment]
https://github.com/CalderCob/EOA-bug-tracker/issues/31

**Comment by TurdFerguson79** [comment]
I have the same issue with Great Barrow.  Completed fine at the time, got the title on my character, but it never showed in my !HC log as completed, and other characters on my account don't have the title.

**Comment by TurdFerguson79** [comment]
He's dead, thank you for reopening that wound, lol

**Comment by echoes-emu** [comment]
As long as you don't delete the character we can award the quest completion retro-actively. Closing as the issue seems to have been fixed by some recent changes. If this happens again (with a _fresh_ completion resetting), please reopen this

**Comment by TurdFerguson79** [comment]
No way to fix my bug then without doing GB again?

Went from server-first to nothing in the blink of an eye, haha.
