### ISSUE TITLE
Hobbit burglar auto attack animation bug

### ISSUE THREAD

**Issue by koriself** [CalderCob/EOA-bug-tracker#55]
So hobbit has 1 auto attack animation that basically locks you from using skills for few moments, the animation im talking about is when you swing your weapon from middle to the sides, this doesnt affect men even if they do similar animation as videos will show. 
I tested with sword dagger, and dagger dagger and to be honest i think its bugged on every weapon. im posting links with videos for an example.
https://youtu.be/iRLZoI5J8DY?si=dO4-oLjE_Vc4jdAC
https://youtu.be/rJ7t0MoM5gE?si=I3N3JqrpOA_mCWiq
https://youtu.be/fj0q5ubdrTc?si=dCIie8B8y9f387K9

**Comment by Lighwan** [comment]
Can vouch for this, the stab animation has much higher dps than slash animation. Massive delay on hobbit burgs

**Comment by echoes-emu** [comment]
Client data issue
