### ISSUE TITLE
[QUEST] A Formal Complaint (multiple separate encounters activating simultaneously)

### ISSUE THREAD

**Issue by TurdFerguson79** [CalderCob/EOA-bug-tracker#58]
A Formal Complaint (Instance)

Encounters should trigger upon the completion of the previous encounter (brigands/rats/brigands-wolves/boss) but instead when you enter the room with the rats, encounters 3, 4 and 5 activate as well, overwhelming the party with ~18 mobs. (Small Fellowship quest)

1. Enter room 2 and activate the rats
2. See if further encounters also activate
3. !nuke rats, wolves, and brigands and laugh evilly

Expected Behavior:

Clear each encounter in turn.  Enter 1st room, kill occupants.  Enter room 2 (rats), kill rats.  After they die, the next brigands have a short script and then activate.

* Quest Giver Location: Future Glassblower Camp above brigand camp in Bullroarer's Sward
* Problem Location: Inside the instance
* Turn in location: Same NPC--Hob Hillbrow

**Comment by TurdFerguson79** [comment]
And since there was some confusion as to whether this was actually a Small Fellowship quest (since the prior objective in the chain is labeled Fellowship):

https://imgur.com/a/DEMcHPN

**Comment by echoes-emu** [comment]
I believe this is already fixed

**Comment by TurdFerguson79** [comment]
Well I'm certainly not going to test it again!  rofl
