### ISSUE TITLE
[BUG] Unable to use inductions while swimming

### ISSUE THREAD

**Issue by ryze1234** [CalderCob/EOA-bug-tracker#6]
### Description of the issue

You seem to be unable to use any inductions while in swimming. Happens to me and also to a friend.

### Steps To Reproduce

1. Go into a water source until you start swimming.
2. Stand still
3. Use induction skill (tried with LM´s Burning Embers, Leechcraft, Tend the Sick, Bearfriend and Ravenlore)
4. Induction bar will instantly be interrupted on use of skill.

### Expected Behavior

You should be able to cast while swimming in water, as long as you stand still of course.

### Where it Happens

Any Water source, that you can swim in.
(Expample: bx115 by122 c0 ox95.4067 oy90.9531 oz375.051 r171 (Instance 0))

### Screenshots

![ScreenShot00025](https://github.com/CalderCob/EOA-bug-tracker/assets/143268041/2b3580ff-2090-4508-becd-2ca1e5f3dbe5)

**Comment by echoes-emu** [comment]
This is already tracked in the internal bugtracker
