### ISSUE TITLE
[BUG] Infinite crafting tools durability

### ISSUE THREAD

**Issue by TrueZiegmaster** [CalderCob/EOA-bug-tracker#61]
### Description of the issue

At the moment, gathering resources does not consume the durability of tools.

### Steps To Reproduce

1. Spend some time to gather ore or something else. (I've gathered more than 100 ore to be sure).
2. Visit any vendor to repair (again to be sure that its not a display error) but durability should still be full.

### Entity Information

Used default non crafted pickaxe for t2 ore gathering.

### Screenshots

Screenshots don't prove anything here i believe, just need a manual check.

**Comment by echoes-emu** [comment]
Tracked internally
