### ISSUE TITLE
[BUG] UI element ProgressBar Drag Box is not movable

### ISSUE THREAD

**Issue by MattStarwalker** [CalderCob/EOA-bug-tracker#63]
### Description of the issue

UI element ProgressBar Drag Box is not movable; all other UI elements do seem to be. As a result is obscured by docked QuickSlot bars/

### Steps To Reproduce

Steps to reproduce the behaviour:
1. toggle visibility of the UI elements
2. try and move the ProgressBar Drag Box

### Expected Behaviour

be able to move the ProgressBar Drag Box

**Comment by woodx319** [comment]
You can move it make sure that you dont have your bags open so that the drag is being blocked by the empty quickslots

**Comment by CalderCob** [comment]
Seems to be a user error, it is possible to move the ProgressBar Box, but bags need to be closed.
