### ISSUE TITLE
Song of Distraction (Minstrel) not working at all

### ISSUE THREAD

**Issue by TurdFerguson79** [CalderCob/EOA-bug-tracker#64]
Easy report.  Skill doesn't work.  It doesn't get resisted, per se, and even worse it aggroes the mob 100% of the time.  Even grey mobs do not receive the effect.

**Comment by TurdFerguson79** [comment]
Update:  it can be resisted, and if it resists, the mobs don't pull.  But ironically if it doesn't resist, they do.

**Comment by echoes-emu** [comment]
Tracked internally
