### ISSUE TITLE
[BUG] Fornost Instance

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#65]
### Description of the issue

A couple of bugs - from reoccuring silence to mobs pulling through walls. Will have video timestamps to help visualize this.

### Steps To Reproduce

1. go into the instance

### Expected Behavior

for the bugs to reoccur

### Where it Happens

Fornost instance

### Entity Information

https://youtu.be/fa5rPBAaSPw?t=201 = continuance silence problem. (in that area specific)
https://youtu.be/fa5rPBAaSPw?t=4970 = mobs pulled through the wall + not sure what trigged the ghosts
https://youtu.be/fa5rPBAaSPw?t=8682 = Last boss braziers are bugged. We used left than right (but the middle adds triggered when we used the right) - then I used the middle and nothing happened. We needed to use the right again for the last buff from boss to be removed. (all minor issues very good (almost bug free) instance.

### Screenshots

https://www.youtube.com/watch?v=fa5rPBAaSPw = whole video
https://www.youtube.com/watch?v=zTC--ADy_d0 = original 2007 video

**Comment by echoes-emu** [comment]
1. Fixed
2. Should be fixed
3. The encounter is scripted correctly
