### ISSUE TITLE
Finely Carved Rallying Horn[BUG] 

### ISSUE THREAD

**Issue by Miti4455** [CalderCob/EOA-bug-tracker#66]
### Description of the issue

Cappy summoning horn doesn't go on its 10 sec cooldown on summoning a member of the party, also it does not consume any traveling rations (should take 5 off the summonee)

### Steps To Reproduce

1. Be in a fellowship
2. Use captains horn to summon a fs member
3. Horn doesn't go on cooldown and checking the summonee it won't take traveling rations

### Expected Behavior

It should go on cooldown on summon confirmation

**Comment by echoes-emu** [comment]
Fixed. The correct amount of rations in this case is 5 btw
