### ISSUE TITLE
[NPC] GA Ivar doesn't Activate

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#67]
### Ivar encounter doesn't start after resetting him.

After resetting Ivar in GA he wouldn't activate. We even tryed going out of the instance and back in again but he just did nothing.

### Steps To Reproduce

1. Pull Ivar out of his arena so he resets.
2. Wait for Ivar to reset.
3. Walk in and see Ivar stay green and not activate.

### Expected Behavior

_After resetting and walking back into Ivar's arena he should activate.

### NPC Information

Typing this after we did the instance so missed this.

### Where it Happens

Ivar in Gath Agarwen.

### Screenshots

No screenshots.

**Comment by echoes-emu** [comment]
Fixed
