### ISSUE TITLE
Book 10 monsters and NPC spawned in Evendim [NPC] 

### ISSUE THREAD

**Issue by TurdFerguson79** [CalderCob/EOA-bug-tracker#69]
Just outside of the Eavespires camp in Northern Emyn Muil [5.5S, 71.9W], Mol Cholum (NPC from Book 10 Chapter 7) is spawned, along with 2 hostile L50 Guaradan Negotiators.

Normally Mol Cholum only shows up when someone with the quest approaches the area, and his Guaradain don't spawn until you interact with him.

**Comment by echoes-emu** [comment]
Fixed
