### ISSUE TITLE
[QUEST] Grave-Rubbings mobs not interacting

### ISSUE THREAD

**Issue by TurdFerguson79** [CalderCob/EOA-bug-tracker#70]
Grave-Rubbings

Quest giver: Forchon (Tinnudir)
Problem location: [9.8S, 61.5W]

There are 4 gravestones which you need to take rubbings from.  Each gravestone will summon a wave of adds which should attack the player.  Instead, they spawn nearby and don't move from their spawn point.  Eventually piling up into large groups.  

Either the player should need to kill all mobs, or if the mobs can't find the player (stealthed or ran away) then they should despawn.

(Apologies for the imprecise /loc data, but my primary objective is not dying and I'm putting in bug reports in between play sessions :D)

**Comment by echoes-emu** [comment]
Fixed
