### ISSUE TITLE
[QUEST] Minor bug during "Shore Up The Fence"

### ISSUE THREAD

**Issue by Shazrah07** [CalderCob/EOA-bug-tracker#71]
### Shore Up The Fence

_Shore Up The Fence._

### Even after completion of the quest there appears to be one "Small Field-Stone" on the ground flashing like you could pick up the item. When attempting to grab the "Small Field-Stone" you will get a "Using this has no effect prompt

_One of the items that the quest has you grab still appears active even when the quest is complete._

### Steps To Reproduce

1. Pick up the "Shore Up The Fence" quest
2. Pick up all the necessary Small, Flat, and Large Field-Stones that the quests asks of you.
3. In one particular spot at "You are at: bx95 by113 c0 ox89.2761 oy55.7509 oz391.178 r221 (Instance 0)" you may potentially see the Small Field Stone flashing, which would mean you could still pick it up for your quest. 

### Expected Behavior

_Normally when a quest has you pick up several items out in the world once it is finished the items that you can pick up stop flashing and appearing as lootable_

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in:_
* You are at: bx94 by114 c0 ox130.417 oy77.6563 oz416.581 r0 (Instance 0)_
* You are at: bx95 by113 c0 ox89.2761 oy55.7509 oz391.178 r221 (Instance 0)
* You are at: bx94 by114 c0 ox130.417 oy77.6563 oz416.581 r0 (Instance 0)_

### Entity Information

_Selection: 0x0315F710000000CE (0x0415F7100000002A)
 DID: 0x70000D64
 Loc: bx95 by113 c0 ox89.1741 oy55.8002 oz390.893 r134 (Instance 0)._

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/143241441/08b26f64-85ed-4ecf-860f-00ed119f73f1)

**Comment by echoes-emu** [comment]
The item flashing is client-side so probably an old issue with this particular item
