### ISSUE TITLE
[QUEST] [Evendim] Ancient Statuary - Large statue pieces do not respawn.

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#72]
### Quest Name

Ancient Statuary

### Description of the issue

Large statue pieces do not respawn.

### Steps To Reproduce

1. Loot Large statue pieces.
2. Wait for respawn.
3. ...

### Expected Behavior

Large statue pieces should respawn.

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in:
* Quest Giver Location: _where you obtained the quest:
* Problem Location: You are at: bx96 by146 c0 ox113.885 oy70.7231 oz343.265 r126 (Instance 0)
* Turn in location: _where you are supposed to finish the quest:

### Entity Information

Can no longer see the item cause it doesn't respawn.

### Screenshots

-No screenshot

**Comment by echoes-emu** [comment]
Fixed
