### ISSUE TITLE
[QUEST] [Evendim] That which I value most need relog to work

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#74]
### Quest Name

That which I value most

### Description of the issue

Performing the /kneel emote doesn't work after accepting the quest. It however does work if you relog after accepting the quest.

### Steps To Reproduce

1. Accept the quest from Gwindeth.
2. /kneel targetting Gwindeth.
3. Quest doesn't complete unless you relog and do it again.

### Expected Behavior

Performing the emote after taking the quest should work without having to relog.

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in:_
* Quest Giver Location: You are at: bx250 by81 c387 ox144.352 oy102.676 oz-362.161 r47 (Instance 0)
* Problem Location: You are at: bx250 by81 c387 ox144.352 oy102.676 oz-362.161 r47 (Instance 0)
* Turn in location: You are at: bx250 by81 c387 ox144.352 oy102.676 oz-362.161 r47 (Instance 0)

### Entity Information
Selection: 0x031FA51000000006 (0x041FA51000000002)
 DID: 0x70009705
 Loc: bx250 by81 c430 ox146.818 oy103.545 oz-362.111 r180 (Instance 0)
 Move table: 0x070003CB
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

### Screenshots

-no screenshot

**Comment by woodx319** [comment]
### Update

You don't need to relog for this. 


- Run a few meters away from Gwindeth and you should see the quest update. 
- After that you'll be able to emote successfully

**Comment by TurdFerguson79** [comment]
Hmm, I feel like I ran around a bit and didn't get it to trigger, but a relog worked for me as well.

**Comment by woodx319** [comment]
https://github.com/echoes-emu/echoes-bt/issues/918
