### ISSUE TITLE
[SKILL] or [TRAIT] LM Storm Lore - Lightning Strike - Gust of Wind

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#75]
### Skill Name

Lightning Storm
Storm Lore
Gust of Wind

### Description of the issue

Damage Type is common damage with these skills, but armour reduction from ancient craft -270 armour does not increase the damage of these skills. Is either the damage type wrong or why does the common damage not increase when armour is reduction

### Steps To Reproduce

1 use one of the three abilities
2 use ancient craft
3 use the same ability from the three original again and compare damage

### Expected Behavior

the common damage with and without the debuff is going to be the same

### Location

x

### Entity Information

x

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/15167869/83c81b67-a973-4c7c-a708-f6cb05d19887)

**Comment by echoes-emu** [comment]
Dupe
