### ISSUE TITLE
[NPC] Goblins in Annúndir aggro even when they are grey

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#76]
### Description of the issue

Goblins in North-Downs, Annúndir, aggro even when they are grey to me.

### Steps To Reproduce

Be high enough level for the goblins to be grey to you and go to: You are at: bx121 by140 c0 ox8.43389 oy66.8843 oz489.893 r31 (Instance 0)

### Expected Behavior

Grey mobs should not be agressive to you.

### NPC Information

Selection: 0x031798C0000001D4
 DID: 0x700017C4
 Loc: bx121 by140 c0 ox18.5838 oy36.8555 oz487.464 r63 (Instance 0)
 Move table: 0x0700018E
 Cosmetic loadout: 0x7000072F
   melee: Axe
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No
### Where it Happens

You are at: bx121 by140 c0 ox8.43389 oy66.8843 oz489.893 r31 (Instance 0)

### Screenshots

-

**Comment by echoes-emu** [comment]
Moved to the internal bugtracker
