### ISSUE TITLE
[SKILL] [Captain] Rallying horn

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#77]
### Skill Name

Finely carved rallying horn.

### Description of the issue

Summoning fellowship members doesn't consume travelling rations and the horn doesn't go on cooldown.

### Steps To Reproduce

Use the horn.

### Expected Behavior

Should consume 5 travelling rations per summon + 10 second cooldown.

### Location

-

### Entity Information

-

### Screenshots

-

**Comment by echoes-emu** [comment]
Dupe of #66
