### ISSUE TITLE
Landmark POI for Swiftbrook (Evendim) not updating [DEED] 

### ISSUE THREAD

**Issue by TurdFerguson79** [CalderCob/EOA-bug-tracker#79]
For the Wilds of Evendim deed, the map POI for Swiftbook normally triggers as you cross the bridge at:

You are at: bx90 by146 c0 ox120.134 oy146.122 oz463.555 r232 (Instance 0)

I tried swimming up the river to see if the trigger area moved, but I went almost to the source before I got scared I'd hit an instant kill wall.  But normally you shouldn't even have to leave the bridge.

**Comment by echoes-emu** [comment]
Fixed
