### ISSUE TITLE
Horses are knocked out after 1 attack[BUG] 

### ISSUE THREAD

**Issue by Stressy23** [CalderCob/EOA-bug-tracker#80]
### Description of the issue

Horses will be knocked out after one attack. In Original SoA, Horses could take 2-3 hits. Only a critical would instantly cancel them.

### Steps To Reproduce

1. Ride horse
2. Get Attacked
3. Get knocked off after first hit lands

### Expected Behavior

Horses can take 2-3 hits, but a critical would instantly cancel them. 

### Where it Happens

Only tried it in the North downs but I assume it happens everywhere.

**Comment by TurdFerguson79** [comment]
I think this is fixed now?  At least, I took a hit today and wasn't dismounted--progress bar went down 1/3

**Comment by Stressy23** [comment]
Man. If this was fixed I might not have died in the moors :(
