### ISSUE TITLE
Minstrel heals not critting

### ISSUE THREAD

**Issue by Tastykake** [CalderCob/EOA-bug-tracker#81]
### Skill Name

Raise the Spirit, Bolster Courage, Inspire Fellows, Triumphant Spirit

### Description of the issue

I am not getting any crit multiplier from critting with any heals.  After spamming myself with Bolster Courage for the deed - Life Singer, I noticed that none of my heals are critting despite having a 7-10% crit chance.  After further watching the numbers raise from my characters head, some of those numbers raise, and grow larger as they are moving upwards.  This is the indicator of a critical effect with a heal but the number produced is the same as a non-crit standard heal.  I have deducted that the crit multiplier for heals for the minstrel are not working.
 
### Steps To Reproduce

1. Heal yourself
2. Heal yourself some more
3. Just keep healing yourself

### Expected Behavior

Expected that even with a low tactical critical strike chance, minstrels should be seeing 1/20 heals be a critical effect and produce a number somewhere in the range of 1.5 - 2 times the size of a standard non-critical heal. My crit chance is 10% and I am getting the crit effect happen about 1 out of every 10-15 casts but without the crit modifier applied.

### Location

I mainly tried to level this in the Prancing Pony Inn.

### Entity Information

N/A

### Screenshots
Standard Heal with Bolster Courage
![minstrelnocrit](https://github.com/CalderCob/EOA-bug-tracker/assets/144131803/c5b2fe68-c19b-41ac-8310-703c239d9604)
vs
Critical Heal with Bolster Courage
![minstrelcrit](https://github.com/CalderCob/EOA-bug-tracker/assets/144131803/b230d92b-9f38-43d2-9ad5-fac0b440dc7f)

Compare the two screen shots.  One number is noticeably bigger from the critical effect but with no multiplier applied.  It is the exact same value as the non-crit standard heal effect

**Comment by Tastykake** [comment]
Bumping this if possible.  This is a big loss of HPS from the main healer class from fellowships and raids and will only continue to be more and more of a healing loss as tactical crit scales with gear towards level cap.

**Comment by samrien** [comment]
I agree that this isn't working as intended:

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/143850917/6dff7184-6c92-454e-8793-39fe81c8ab53)

**Comment by echoes-emu** [comment]
Tracked internally
