### ISSUE TITLE
[BUG] Auto-attack timer resets when spamming keys

### ISSUE THREAD

**Issue by karasally** [CalderCob/EOA-bug-tracker#82]
### Description of the issue

Auto-attack timer seems to reset when spamming skill that is in either of these 2 states:
1. On cooldown (Tested with Suprise Strike, Aim, Dust In the Eyes, Ready And Able)
2. Requires some kind of event (I tested it with Doubled-Edged Strike, which requires Burglars' Advantage to be used. This didn't work with Find Footing, which requires player to be stunned)

### Steps To Reproduce

1. Attack monster
2. Spam skill that is on cooldown or requires an event

### Expected Behavior

Auto-attack timer should be independent of skill use.
Auto-attack should execute when no skill is animating.

### Where it Happens

With any monster.

### Screenshots

Burglar: https://www.youtube.com/watch?v=tfnfGOhYSLw
Champion with Blade Storm spam: https://www.youtube.com/watch?v=VFaqQgoBZcI

**Comment by woodx319** [comment]
> Auto-attack timer should be independent of skill use.
Why?


The current system incentivizes actually deploying your skills properly and weaving your auto attacks and not spamming your skills incoherently.

**Comment by karasally** [comment]
> The current system incentivizes actually deploying your skills properly and weaving your auto attacks and not spamming your skills incoherently.

Spamming skills doesn't mean incoherent use of skills.

Because if I press a skill that is on CD or that is unavailable to use due to insufficient Fervor amount or because that skill is second in chain (like Double-Edged Strike) then auto-attack should still trigger.
This even stops the auto-attack timer when I use Aim, Dust In The Eyes, Ready And Able when they are on CD.

Why should auto-attack timer reset each time I use a skill that is on CD?

**Comment by woodx319** [comment]
> Why should auto-attack timer reset each time I use a skill that is on CD?

because it rewards people that don't mess up their skill clicks. your char can do one thing at a time it's similar almost to a runescape tick system. if your guy is trying to auto attack but you tell it to skill then it doesn't auto attack (because you told it to skill) 

if I can find any i'll share vid of skill spamming from SOA on youtube

**Comment by woodx319** [comment]
this is Volume I patch so not bk 11 but early on in SOA. 

at 4 seconds they do their melee skill and then do reveal weakness 3 times in a row, no auto attack


https://www.youtube.com/watch?v=yqqiuHHrv5E

**Comment by karasally** [comment]
I see, fair enough then.

**Comment by woodx319** [comment]
https://github.com/echoes-emu/echoes-bt/issues/1083
