### ISSUE TITLE
[QUEST] Mountain Raiders - Head-smasher worms don't aggro.

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#86]
### Quest Name

Mountain Raiders

### Description of the issue

Head-Smasher npc has two worms next to him that don't aggro when you pull him. You are at: bx178 by111 c0 ox7.3815 oy104.071 oz614.16 r50 (Instance 0)

### Steps To Reproduce

1. Attack the Head-Smasher without being in range of the worms.
2. ...
3. ...

### Expected Behavior

The two worms next to him should aggro when you pull him.

### Locations

You are at: bx178 by111 c0 ox7.3815 oy104.071 oz614.16 r50 (Instance 0)

### Entity Information

-

### Screenshots

-

**Comment by echoes-emu** [comment]
This is the correct behavior
