### ISSUE TITLE
[QUEST] The Last Ingot - Halmur Stoneshaper not working

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#87]
### Quest Name

The Last Ingot

### Description of the issue

-Bring the stolen dwarf-gold ingot to Halmur Stoneshaper. After talking to him he doesn't do anything and is no longer working.

### Steps To Reproduce

1. Be on the correct quest step.
2. Talk to Halmur Stoneshaper.
3. ...

### Expected Behavior

He is supposed to do some rp and then go back to being active.

### Locations

_Use /loc in-game to obtain the positions of the following places and paste it in: You are at: bx250 by131 c2 ox-3.3511 oy26.4328 oz-80.674 r234 (Instance 0)
* Quest Giver Location: _where you obtained the quest: You are at: bx250 by131 c2 ox-3.3511 oy26.4328 oz-80.674 r234 (Instance 0)
* Problem Location: _where the problem occurs: You are at: bx250 by131 c2 ox-3.3511 oy26.4328 oz-80.674 r234 (Instance 0)
* Turn in location: _where you are supposed to finish the quest: You are at: bx250 by131 c2 ox-3.3511 oy26.4328 oz-80.674 r234 (Instance 0)

### Entity Information

Selection: 0x031FA83000000015 (0x041FA83000000002)
 DID: 0x7000012E
 Loc: bx250 by131 c2 ox-4.05496 oy27.5328 oz-80.6236 r5 (Instance 0)
 Move table: 0x070001E7
State stack:
(Patrol) PatrolBox @ 0.25x
(Drama) drama_onelastingot_ending
(Interacting)
(Interacting)
(Interacting)
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
Drama: drama_onelastingot_ending

### Screenshots

-

**Comment by echoes-emu** [comment]
This should work now
