### ISSUE TITLE
[QUEST]  Murder in the Ruins - multiple waves spawning simultaneously

### ISSUE THREAD

**Issue by TurdFerguson79** [CalderCob/EOA-bug-tracker#88]
Quest giver:  Helechir (Tinnudir keep)
Quest: Murder in the ruins
Quest type: Solo

Not 100% sure, but I believe there should be 3-4 waves of 3 mobs apiece for this solo quest--I just attempted it and 9 spawned initially and attacked simultaneously (though some of them were stealthed and entered the fight a bit later as they had to sneak over).

Expected behavior: multiple waves of adds in a quantity manageable for a solo player + signature NPC

**Comment by echoes-emu** [comment]
Fixed
