### ISSUE TITLE
Stealth detection seems wonky/wrong [BUG] 

### ISSUE THREAD

**Issue by togreglove** [CalderCob/EOA-bug-tracker#89]
### Description of the issue

I am a Loremaster and often use Sign of Power: Vigilance and/or the pet enhancing trait to increase my stealth detection.
There are 2 indicators for stealth detection, one that looks kind of like an english B, the other is a single mark.
As far as I know, the single mark indicates you are aggroed and  are in combat, the stealth mob comes out of stealth and attacks.
That seems to be working fine regardless of stealth detection.
However, the B indicator is supposed to indicate there is a stealthed creature in the area without aggroing them and show you them creeping about so you can decide to engage/avoid them. 
This is where my memory is vague. I distinctly remember using stealth detection to avoid stealthed mobs in this way, but I have no evidence that this is correct.

If my recollection is correct, the game does *not* expose their location and you are left knowing there is a stealthed mob, but not being able to use this knowledge to avoid/engage the creature.

[Edit: wanted to note this behavior will have strong implications for future PvMP play]

### Steps To Reproduce

1. Go to the roads/fields near Tinnudir.
2. Play loremaster and equip the pet trait that increases stealth detection.
3. Cast Sign of Power: Vigilance
4. Run around between mobs till you see a stealth indicator
5. If it's the B, note that you have no clue what is stealthed, where it is, or what direction you should go to be safe or engage.

### Expected Behavior

Stealth detection should allow you to locate stealthed creatures before they can attack, so you can make intelligent decisions based on enhanced knowledge.

### Where it Happens

I first noticed it with wolves in Lone Lands, but didn't really make note of the issue till I had my active stealth detection running in Evendim.

### Entity Information

Stealthed creatures

**Comment by sjstrazdus** [comment]
What you described is how it has always worked and still works in retail.  I think you just got confused because you never managed to reveal a mob without aggroing it.

The B symbol has always indicated that there is a stealth mob near by, but it is not revealed to you.

The single squiggle indicates there is a stealth mob near by and it will be revealed to you.  It may or may not have aggroed to you.  It all depends how close you got before you detected it.  The LM skill is supposed to help you do this more reliably from farther away.

There's no symbol that indicates detected and aggroed.  I find it helpful to enable the skill queue display in the options.  when it appears on screen you are in combat, and it disappears when you are out of combat.  I don't find it useful to see what skill is queued, just to see if I aggroed something while I'm running around.

**Comment by togreglove** [comment]
Aha, my recollection was indeed incorrect. In that case, the single squiggle is the one acting strange, as even will all my stealth detection up, I have never had an instance where I noticed a stealthed mob this way without it having already aggroed...to the point that I assumed the squiggle indicated an attack. Will monitor to see if it is possible to notice with a squiggle without combat immediately starting.

**Comment by togreglove** [comment]
Or, perhaps *enhanced stealth detection is not working*, and I am just on top of the mob when I notice them because I am not seeing farther than aggro range. Which seems more likely at this point.

**Comment by togreglove** [comment]
Ok, tested it a bit. Enhanced detection is definitely not helping. As a matter of fact, I'd say that detection in general (squiggly) is 0 range.  Twice now, I encountered the "B" sigil. I put up all my enhanced senses (pet trait and spell) and moved around in microsteps. When I encountered the stealthed creature, it appeared right beside me and attacked. I know the sample test size is low, but it seems extremely odd that it happened this way twice randomly.

**Comment by sjstrazdus** [comment]
I just tested some too.  I went to the area with all the stealth wolves in Minas Eriol on my level 29 champ (so everything is grey).  I wasn't able to detect any wolves without basically stepping on them.  Even if I stood and stared at a spot for 30 seconds nothing would be detected until I walked up to the spot.

Also last week I stealthed a level 4 burglar all the way to the watch stones in Angmar and another to the Misty Mountains.  I noticed it was remarkably easy as long as I stayed in stealth.  I thought this meant I was good, but looking back on it, I think the monsters aren't very good at detecting player stealth either.

**Comment by sluwe-vos** [comment]
https://youtu.be/6IeFT0UCkI8

visual confirmation that +3 stealth detection has zero impact

**Comment by CalderCob** [comment]
#124

**Comment by Stressy23** [comment]
I was able to stealth directly in front of red mobs on my burglar many times. 

Stealth works, but stealth levels are not currently working. 

Stealth can be detected through, but the level of stealth should matter
