### ISSUE TITLE
Bees in the Shire [NPC] 

### ISSUE THREAD

**Issue by SpinexLive** [CalderCob/EOA-bug-tracker#9]
**Description of the issue** ```The great willow Bee's are all normal ranked and should be swarms. ```
**Steps To Reproduce** ```complete quests around the Great Willow```
**Where it Happens** ```The great Willow```
** Entity Information** ```Adelard's chapter quest```

This bug was logged via a Kin member of the Silver Blades.

**Comment by echoes-emu** [comment]
Please provide the /loc and !info as requested in the bug template

**Comment by SpinexLive** [comment]
Unable to provide sorry I will ensure future bugs logged by the Kin are done correctly

**Comment by CalderCob** [comment]
Should be fixed after spawn update.
