### ISSUE TITLE
[TRAIT] The Experts guide to Dirty fighting pages did not consume

### ISSUE THREAD

**Issue by Stressy23** [CalderCob/EOA-bug-tracker#91]
### Skill Name

Exposed Throat

### Description of the issue

The 8 pages needed to acquire the skill are not consumed on use, I am not 2/8 on the deed but the pages are still in my inventory. May apply to other legendary traits with tradable pages. 

### Steps To Reproduce

1. Attempt legendary trait with tradable pages
2. acquire pages and see if they are consumed. 

### Expected Behavior

Pages for the deed should be consumed on use. 

### Screenshots

![image](https://github.com/CalderCob/EOA-bug-tracker/assets/122374802/b7fb4e4d-5753-46b7-b732-47b2cc6df9b0)

**Comment by echoes-emu** [comment]
Moved to internal bugtracker
