### ISSUE TITLE
Ancient Craft + Lightning Storm

### ISSUE THREAD

**Issue by sluwe-vos** [CalderCob/EOA-bug-tracker#92]
### Skill Name

Ancient Craft + Lightning Storm - Lore-master

### Description of the issue

When two Lore-masters use Ancient Craft on the same target, only the Lore-master who used it last can follow up with lightning storm

### Steps To Reproduce

1. LM 1 = use ancient craft 
2. LM 2 = use ancient craft on same target
3. LM 1 = use lightning storm (fail)
4. LM 2 = use lightning storm (works)

### Expected Behavior

for it to cancel lightning storm from LM 1

### Location

anywhere

### Entity Information

it is not

### Screenshots

https://www.youtube.com/watch?v=84gNmUtMrU8

**Comment by echoes-emu** [comment]
This seems to be WAI as per SoA data. The 2nd LM's Ancient Craft overrides the older one and Lightning Storm requires the LM's _own_ Ancient Craft to be present on the target
