### ISSUE TITLE
[NPC] Fornost - Megoriath doesn't knock-back

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#95]
### Description of the issue

Boss Megoriath is not using his knock-back skill.

### Steps To Reproduce

Nothing specific happend we just did the boss fight.

### Expected Behavior

From what we remember he is supposed to use a knock-back skill to make use of the arena silencing ppl.
Also on the closed beta video he is doing the knock back: https://www.youtube.com/watch?v=eExBmCukVD8

### NPC Information

Doing the report after we did the dungeon so didn't !info him.

### Where it Happens

Fornost

### Screenshots

-

**Comment by echoes-emu** [comment]
Moved to internal bugtracker
