### ISSUE TITLE
[NPC] Fornost - Remmenaeg braziers and adds WAI?

### ISSUE THREAD

**Issue by Sindalatest** [CalderCob/EOA-bug-tracker#96]
### Description of the issue

The Braziers during the Remmenaeg boss fight in Fornost visually go out but Remmenaeg doesn't get his health regen buff back during the entire fight while the braziers are not burning. 

Also the east brazier spawns two ghosts at the north brazier location, and the north brazier doesn't spawn any adds. 
### Steps To Reproduce

Nothing specific happend we just did the boss encounter.

### Expected Behavior

In our memory the braziers would go out after a certain amount of time giving the boss his health regen buff back. And we thought the east brazier was supposed to spawn whights and the north one the ghosts. WAI?

### NPC Information

Reporting after we did the instance so didn't !info him.

### Where it Happens

Fornost.

### Screenshots

-

**Comment by echoes-emu** [comment]
Yes this is all WAI
