### ISSUE TITLE
[BUG] ABC music system (seemingly) permanently broken

### ISSUE THREAD

**Issue by Lighwan** [CalderCob/EOA-bug-tracker#97]
At first, playing music worked perfectly
but now

Doing /music works
actually doing /play or using the number keys to play notes produces no sound 
leaving /music gives the error
"You must be in music mode to play a song."

Does not fix itself on relog/client restart
here is the file it broke on (i believe)
[BWV1005.txt](https://github.com/CalderCob/EOA-bug-tracker/files/12622420/BWV1005.txt)

**Comment by Lighwan** [comment]
LOL just found out what causes this 1minute after posting bug report

Playing music breaks completely while "Low latency mode" in settings is turned off

**Comment by echoes-emu** [comment]
ABC files are completely client-side. In general, modern ABC files are unlikely to work unless they're pretty simple.
